// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/department.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepartmentRequest) Reset() {
	*x = GetDepartmentRequest{}
	mi := &file_proto_department_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentRequest) ProtoMessage() {}

func (x *GetDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_department_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentRequest.ProtoReflect.Descriptor instead.
func (*GetDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_department_proto_rawDescGZIP(), []int{0}
}

func (x *GetDepartmentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDepartmentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DepartmentName string                 `protobuf:"bytes,2,opt,name=department_name,json=departmentName,proto3" json:"department_name,omitempty"`
	Status         bool                   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Remark         string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	Deleting       bool                   `protobuf:"varint,5,opt,name=deleting,proto3" json:"deleting,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDepartmentResponse) Reset() {
	*x = GetDepartmentResponse{}
	mi := &file_proto_department_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentResponse) ProtoMessage() {}

func (x *GetDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_department_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentResponse.ProtoReflect.Descriptor instead.
func (*GetDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_department_proto_rawDescGZIP(), []int{1}
}

func (x *GetDepartmentResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetDepartmentResponse) GetDepartmentName() string {
	if x != nil {
		return x.DepartmentName
	}
	return ""
}

func (x *GetDepartmentResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetDepartmentResponse) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *GetDepartmentResponse) GetDeleting() bool {
	if x != nil {
		return x.Deleting
	}
	return false
}

type BatchGetDepartmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetDepartmentsRequest) Reset() {
	*x = BatchGetDepartmentsRequest{}
	mi := &file_proto_department_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetDepartmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetDepartmentsRequest) ProtoMessage() {}

func (x *BatchGetDepartmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_department_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetDepartmentsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetDepartmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_department_proto_rawDescGZIP(), []int{2}
}

func (x *BatchGetDepartmentsRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type BatchGetDepartmentsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Departments   []*GetDepartmentResponse `protobuf:"bytes,1,rep,name=departments,proto3" json:"departments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetDepartmentsResponse) Reset() {
	*x = BatchGetDepartmentsResponse{}
	mi := &file_proto_department_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetDepartmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetDepartmentsResponse) ProtoMessage() {}

func (x *BatchGetDepartmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_department_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetDepartmentsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetDepartmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_department_proto_rawDescGZIP(), []int{3}
}

func (x *BatchGetDepartmentsResponse) GetDepartments() []*GetDepartmentResponse {
	if x != nil {
		return x.Departments
	}
	return nil
}

var File_proto_department_proto protoreflect.FileDescriptor

const file_proto_department_proto_rawDesc = "" +
	"\n" +
	"\x16proto/department.proto\x12\n" +
	"department\"&\n" +
	"\x14GetDepartmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x9c\x01\n" +
	"\x15GetDepartmentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x0fdepartment_name\x18\x02 \x01(\tR\x0edepartmentName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\bR\x06status\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\x12\x1a\n" +
	"\bdeleting\x18\x05 \x01(\bR\bdeleting\".\n" +
	"\x1aBatchGetDepartmentsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"b\n" +
	"\x1bBatchGetDepartmentsResponse\x12C\n" +
	"\vdepartments\x18\x01 \x03(\v2!.department.GetDepartmentResponseR\vdepartments2\xd1\x01\n" +
	"\x11DepartmentService\x12T\n" +
	"\rGetDepartment\x12 .department.GetDepartmentRequest\x1a!.department.GetDepartmentResponse\x12f\n" +
	"\x13BatchGetDepartments\x12&.department.BatchGetDepartmentsRequest\x1a'.department.BatchGetDepartmentsResponseB&Z$vue-element-plus-admin/backend/pb;pbb\x06proto3"

var (
	file_proto_department_proto_rawDescOnce sync.Once
	file_proto_department_proto_rawDescData []byte
)

func file_proto_department_proto_rawDescGZIP() []byte {
	file_proto_department_proto_rawDescOnce.Do(func() {
		file_proto_department_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_department_proto_rawDesc), len(file_proto_department_proto_rawDesc)))
	})
	return file_proto_department_proto_rawDescData
}

var file_proto_department_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_department_proto_goTypes = []any{
	(*GetDepartmentRequest)(nil),        // 0: department.GetDepartmentRequest
	(*GetDepartmentResponse)(nil),       // 1: department.GetDepartmentResponse
	(*BatchGetDepartmentsRequest)(nil),  // 2: department.BatchGetDepartmentsRequest
	(*BatchGetDepartmentsResponse)(nil), // 3: department.BatchGetDepartmentsResponse
}
var file_proto_department_proto_depIdxs = []int32{
	1, // 0: department.BatchGetDepartmentsResponse.departments:type_name -> department.GetDepartmentResponse
	0, // 1: department.DepartmentService.GetDepartment:input_type -> department.GetDepartmentRequest
	2, // 2: department.DepartmentService.BatchGetDepartments:input_type -> department.BatchGetDepartmentsRequest
	1, // 3: department.DepartmentService.GetDepartment:output_type -> department.GetDepartmentResponse
	3, // 4: department.DepartmentService.BatchGetDepartments:output_type -> department.BatchGetDepartmentsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_department_proto_init() }
func file_proto_department_proto_init() {
	if File_proto_department_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_department_proto_rawDesc), len(file_proto_department_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_department_proto_goTypes,
		DependencyIndexes: file_proto_department_proto_depIdxs,
		MessageInfos:      file_proto_department_proto_msgTypes,
	}.Build()
	File_proto_department_proto = out.File
	file_proto_department_proto_goTypes = nil
	file_proto_department_proto_depIdxs = nil
}
