// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/user_management.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountUsersByDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  int64                  `protobuf:"varint,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountUsersByDepartmentRequest) Reset() {
	*x = CountUsersByDepartmentRequest{}
	mi := &file_proto_user_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountUsersByDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountUsersByDepartmentRequest) ProtoMessage() {}

func (x *CountUsersByDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountUsersByDepartmentRequest.ProtoReflect.Descriptor instead.
func (*CountUsersByDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_management_proto_rawDescGZIP(), []int{0}
}

func (x *CountUsersByDepartmentRequest) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

type CountUsersByDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountUsersByDepartmentResponse) Reset() {
	*x = CountUsersByDepartmentResponse{}
	mi := &file_proto_user_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountUsersByDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountUsersByDepartmentResponse) ProtoMessage() {}

func (x *CountUsersByDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountUsersByDepartmentResponse.ProtoReflect.Descriptor instead.
func (*CountUsersByDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_management_proto_rawDescGZIP(), []int{1}
}

func (x *CountUsersByDepartmentResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_user_management_proto protoreflect.FileDescriptor

const file_proto_user_management_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/user_management.proto\x12\x0eusermanagement\"D\n" +
	"\x1dCountUsersByDepartmentRequest\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\x03R\fdepartmentId\"6\n" +
	"\x1eCountUsersByDepartmentResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count2\x90\x01\n" +
	"\x15UserManagementService\x12w\n" +
	"\x16CountUsersByDepartment\x12-.usermanagement.CountUsersByDepartmentRequest\x1a..usermanagement.CountUsersByDepartmentResponseB&Z$vue-element-plus-admin/backend/pb;pbb\x06proto3"

var (
	file_proto_user_management_proto_rawDescOnce sync.Once
	file_proto_user_management_proto_rawDescData []byte
)

func file_proto_user_management_proto_rawDescGZIP() []byte {
	file_proto_user_management_proto_rawDescOnce.Do(func() {
		file_proto_user_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_management_proto_rawDesc), len(file_proto_user_management_proto_rawDesc)))
	})
	return file_proto_user_management_proto_rawDescData
}

var file_proto_user_management_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_user_management_proto_goTypes = []any{
	(*CountUsersByDepartmentRequest)(nil),  // 0: usermanagement.CountUsersByDepartmentRequest
	(*CountUsersByDepartmentResponse)(nil), // 1: usermanagement.CountUsersByDepartmentResponse
}
var file_proto_user_management_proto_depIdxs = []int32{
	0, // 0: usermanagement.UserManagementService.CountUsersByDepartment:input_type -> usermanagement.CountUsersByDepartmentRequest
	1, // 1: usermanagement.UserManagementService.CountUsersByDepartment:output_type -> usermanagement.CountUsersByDepartmentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_management_proto_init() }
func file_proto_user_management_proto_init() {
	if File_proto_user_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_management_proto_rawDesc), len(file_proto_user_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_management_proto_goTypes,
		DependencyIndexes: file_proto_user_management_proto_depIdxs,
		MessageInfos:      file_proto_user_management_proto_msgTypes,
	}.Build()
	File_proto_user_management_proto = out.File
	file_proto_user_management_proto_goTypes = nil
	file_proto_user_management_proto_depIdxs = nil
}
