// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence_cleanup.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEligibleCommandReceipts = `-- name: CountEligibleCommandReceipts :one

SELECT count(*) FROM organization_command_receipts
WHERE status IN ('succeeded', 'rejected')
  AND completed_at <= $1::timestamptz - interval '30 days'
`

// evidence_cleanup.sql
// Organization owner-local evidence cleanup (data-model.md "Retention and
// cleanup matrix", T078). Organization evidence is always terminal: receipts
// are written in the succeeded/rejected state only (schema CHECK) and inbox
// dedupe rows exist only after successful processing — so there is no
// unresolved Organization evidence to block a purge. The inbox minimum is
// "at least as long as the producer outbox can be replayed"; the 30-day
// processing floor plus the Platform coordinator's most-conservative-cutoff
// cross-owner agreement uphold that without any cross-owner SQL.
func (q *Queries) CountEligibleCommandReceipts(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countEligibleCommandReceipts, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEligibleInboxMessages = `-- name: CountEligibleInboxMessages :one
SELECT count(*) FROM organization_inbox_messages
WHERE processed_at <= $1::timestamptz - interval '30 days'
`

func (q *Queries) CountEligibleInboxMessages(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countEligibleInboxMessages, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const oldestReplayableEvidenceAt = `-- name: OldestReplayableEvidenceAt :one
SELECT
    (SELECT min(completed_at)::timestamptz FROM organization_command_receipts
      WHERE status IN ('succeeded', 'rejected')) AS oldest_receipt_completed_at,
    (SELECT min(processed_at)::timestamptz FROM organization_inbox_messages) AS oldest_processed_at
`

type OldestReplayableEvidenceAtRow struct {
	OldestReceiptCompletedAt pgtype.Timestamptz `json:"oldest_receipt_completed_at"`
	OldestProcessedAt        pgtype.Timestamptz `json:"oldest_processed_at"`
}

// The earliest retained Organization terminal timestamps (oldest receipt
// completion and oldest inbox processing, each NULL when absent). The adapter
// computes the replay floor as min(these) + 30 days — the earliest cutoff at
// which any Organization evidence becomes eligible.
func (q *Queries) OldestReplayableEvidenceAt(ctx context.Context) (OldestReplayableEvidenceAtRow, error) {
	row := q.db.QueryRow(ctx, oldestReplayableEvidenceAt)
	var i OldestReplayableEvidenceAtRow
	err := row.Scan(&i.OldestReceiptCompletedAt, &i.OldestProcessedAt)
	return i, err
}

const purgeEligibleCommandReceipts = `-- name: PurgeEligibleCommandReceipts :execrows
DELETE FROM organization_command_receipts
WHERE status IN ('succeeded', 'rejected')
  AND completed_at <= $1::timestamptz - interval '30 days'
`

func (q *Queries) PurgeEligibleCommandReceipts(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeEligibleCommandReceipts, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeEligibleInboxMessages = `-- name: PurgeEligibleInboxMessages :execrows
DELETE FROM organization_inbox_messages
WHERE processed_at <= $1::timestamptz - interval '30 days'
`

func (q *Queries) PurgeEligibleInboxMessages(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeEligibleInboxMessages, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
