// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMembershipsForUsers = `-- name: DeleteMembershipsForUsers :exec

DELETE FROM organization_user_departments
WHERE user_id = ANY($1::bigint[])
`

// inbox.sql
// Terminal IAM user-deleted consumption (US2, contracts/organization-application.md).
// The service deletes the membership state rows and inserts the successful
// dedupe row in one Organization transaction; a handler failure rolls both
// back. Never references IAM tables.
// Full-batch physical cleanup (terminal deletion path); absent rows are a
// normal no-op.
func (q *Queries) DeleteMembershipsForUsers(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, deleteMembershipsForUsers, dollar_1)
	return err
}

const getInboxMessage = `-- name: GetInboxMessage :one
SELECT event_id, handler_name, event_type, event_version, aggregate_id,
       aggregate_version, received_at, processed_at
FROM organization_inbox_messages
WHERE event_id = $1 AND handler_name = $2
`

type GetInboxMessageParams struct {
	EventID     pgtype.UUID `json:"event_id"`
	HandlerName string      `json:"handler_name"`
}

// Dedupe check for (event_id, handler_name). Missing = not yet processed.
func (q *Queries) GetInboxMessage(ctx context.Context, arg GetInboxMessageParams) (OrganizationInboxMessage, error) {
	row := q.db.QueryRow(ctx, getInboxMessage, arg.EventID, arg.HandlerName)
	var i OrganizationInboxMessage
	err := row.Scan(
		&i.EventID,
		&i.HandlerName,
		&i.EventType,
		&i.EventVersion,
		&i.AggregateID,
		&i.AggregateVersion,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getInboxMetrics = `-- name: GetInboxMetrics :many
SELECT metric_key, count
FROM organization_inbox_metrics
ORDER BY metric_key
`

// Read the Organization-owned cumulative inbox counters (T066 table) for
// metrics exposition (T074). Key-value rows; absent keys simply don't exist.
func (q *Queries) GetInboxMetrics(ctx context.Context) ([]OrganizationInboxMetric, error) {
	rows, err := q.db.Query(ctx, getInboxMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationInboxMetric{}
	for rows.Next() {
		var i OrganizationInboxMetric
		if err := rows.Scan(&i.MetricKey, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementInboxMetric = `-- name: IncrementInboxMetric :exec
INSERT INTO organization_inbox_metrics(metric_key, count) VALUES ($1, $2)
ON CONFLICT (metric_key) DO UPDATE
    SET count = organization_inbox_metrics.count + EXCLUDED.count
`

type IncrementInboxMetricParams struct {
	MetricKey string `json:"metric_key"`
	Count     int64  `json:"count"`
}

// Cumulative inbox observability counter (T066): processed / duplicates /
// handler-failure outcomes. Atomic delta upsert on the Organization-owned
// metrics table; never affects handler semantics.
func (q *Queries) IncrementInboxMetric(ctx context.Context, arg IncrementInboxMetricParams) error {
	_, err := q.db.Exec(ctx, incrementInboxMetric, arg.MetricKey, arg.Count)
	return err
}

const insertInboxMessage = `-- name: InsertInboxMessage :exec
INSERT INTO organization_inbox_messages (
    event_id, handler_name, event_type, event_version, aggregate_id,
    aggregate_version, received_at, processed_at)
VALUES ($1, $2, $3, $4, $5, $6, now(), now())
ON CONFLICT (event_id, handler_name) DO NOTHING
`

type InsertInboxMessageParams struct {
	EventID          pgtype.UUID `json:"event_id"`
	HandlerName      string      `json:"handler_name"`
	EventType        string      `json:"event_type"`
	EventVersion     int32       `json:"event_version"`
	AggregateID      string      `json:"aggregate_id"`
	AggregateVersion int64       `json:"aggregate_version"`
}

// Successful-processing evidence; ON CONFLICT DO NOTHING is belt-and-braces
// for a racing redelivery, never an overwrite.
func (q *Queries) InsertInboxMessage(ctx context.Context, arg InsertInboxMessageParams) error {
	_, err := q.db.Exec(ctx, insertInboxMessage,
		arg.EventID,
		arg.HandlerName,
		arg.EventType,
		arg.EventVersion,
		arg.AggregateID,
		arg.AggregateVersion,
	)
	return err
}
