// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships_mutations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO organization_user_departments (user_id, department_id, membership_version)
VALUES ($1, $2, $3)
RETURNING user_id, department_id, membership_version, created_at, updated_at
`

type CreateMembershipParams struct {
	UserID            int64       `json:"user_id"`
	DepartmentID      pgtype.Int8 `json:"department_id"`
	MembershipVersion int64       `json:"membership_version"`
}

// First state row: real department (set) or null tombstone (clear).
func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (OrganizationUserDepartment, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.UserID, arg.DepartmentID, arg.MembershipVersion)
	var i OrganizationUserDepartment
	err := row.Scan(
		&i.UserID,
		&i.DepartmentID,
		&i.MembershipVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockMembershipByUserID = `-- name: LockMembershipByUserID :one

SELECT user_id, department_id, membership_version, created_at, updated_at
FROM organization_user_departments
WHERE user_id = $1
FOR UPDATE
`

// memberships_mutations.sql
// Versioned membership mutations (US2, contracts/organization-application.md).
// The service serializes each mutation inside one Organization-local
// transaction: lock the state row FOR UPDATE, decide against the expected
// version, then create/update. All references stay inside Organization-owned
// tables (ownership matrix T016) — never IAM tables.
// Row-level lock for CAS decision-making. Missing row = no state established
// (a normal empty result for the decision, not an error).
func (q *Queries) LockMembershipByUserID(ctx context.Context, userID int64) (OrganizationUserDepartment, error) {
	row := q.db.QueryRow(ctx, lockMembershipByUserID, userID)
	var i OrganizationUserDepartment
	err := row.Scan(
		&i.UserID,
		&i.DepartmentID,
		&i.MembershipVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMembership = `-- name: UpdateMembership :one
UPDATE organization_user_departments
SET department_id = $2,
    membership_version = $3,
    updated_at = now()
WHERE user_id = $1
RETURNING user_id, department_id, membership_version, created_at, updated_at
`

type UpdateMembershipParams struct {
	UserID            int64       `json:"user_id"`
	DepartmentID      pgtype.Int8 `json:"department_id"`
	MembershipVersion int64       `json:"membership_version"`
}

// Version-bearing replacement under the service's CAS decision (the row is
// locked first; the WHERE is defense in depth, not the decision point).
func (q *Queries) UpdateMembership(ctx context.Context, arg UpdateMembershipParams) (OrganizationUserDepartment, error) {
	row := q.db.QueryRow(ctx, updateMembership, arg.UserID, arg.DepartmentID, arg.MembershipVersion)
	var i OrganizationUserDepartment
	err := row.Scan(
		&i.UserID,
		&i.DepartmentID,
		&i.MembershipVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
