// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchGetUserMemberships = `-- name: BatchGetUserMemberships :many
SELECT m.user_id, m.department_id, d.name AS department_name,
       m.membership_version, m.created_at, m.updated_at
FROM organization_user_departments m
LEFT JOIN departments d ON d.id = m.department_id
WHERE m.user_id = ANY($1::bigint[])
ORDER BY m.user_id
`

type BatchGetUserMembershipsRow struct {
	UserID            int64              `json:"user_id"`
	DepartmentID      pgtype.Int8        `json:"department_id"`
	DepartmentName    pgtype.Text        `json:"department_name"`
	MembershipVersion int64              `json:"membership_version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// One bounded query for the current list page; users without a state row are
// simply absent from the result (the BFF maps absence to no-department).
func (q *Queries) BatchGetUserMemberships(ctx context.Context, dollar_1 []int64) ([]BatchGetUserMembershipsRow, error) {
	rows, err := q.db.Query(ctx, batchGetUserMemberships, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchGetUserMembershipsRow{}
	for rows.Next() {
		var i BatchGetUserMembershipsRow
		if err := rows.Scan(
			&i.UserID,
			&i.DepartmentID,
			&i.DepartmentName,
			&i.MembershipVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserMembershipByUserID = `-- name: GetUserMembershipByUserID :one

SELECT m.user_id, m.department_id, d.name AS department_name,
       m.membership_version, m.created_at, m.updated_at
FROM organization_user_departments m
LEFT JOIN departments d ON d.id = m.department_id
WHERE m.user_id = $1
`

type GetUserMembershipByUserIDRow struct {
	UserID            int64              `json:"user_id"`
	DepartmentID      pgtype.Int8        `json:"department_id"`
	DepartmentName    pgtype.Text        `json:"department_name"`
	MembershipVersion int64              `json:"membership_version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// memberships.sql
// Read-side queries for organization_user_departments (US1 BFF composition;
// the full versioned membership mutations land with US2/T035-T036).
// All references stay inside Organization-owned tables (ownership matrix T016):
// organization_user_departments + departments only — never IAM tables.
// Missing row means "Organization state never established" (normal empty
// result for the BFF, not an error). The department name is joined so the
// profile composition needs no per-row lookup.
func (q *Queries) GetUserMembershipByUserID(ctx context.Context, userID int64) (GetUserMembershipByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getUserMembershipByUserID, userID)
	var i GetUserMembershipByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.DepartmentID,
		&i.DepartmentName,
		&i.MembershipVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserIDsByDepartment = `-- name: ListUserIDsByDepartment :many
SELECT user_id
FROM organization_user_departments
WHERE department_id = $1
ORDER BY user_id
`

// Complete deterministic candidate-id set for the department filter; the IAM
// side applies its own filters and pagination over these ids.
func (q *Queries) ListUserIDsByDepartment(ctx context.Context, departmentID pgtype.Int8) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUserIDsByDepartment, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
