// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminWorkflow struct {
	OperationID               pgtype.UUID        `json:"operation_id"`
	OperationType             string             `json:"operation_type"`
	IdempotencyKey            pgtype.Text        `json:"idempotency_key"`
	RequestFingerprint        string             `json:"request_fingerprint"`
	ActorUserID               int64              `json:"actor_user_id"`
	SubjectUserID             pgtype.Int8        `json:"subject_user_id"`
	State                     string             `json:"state"`
	CurrentStep               string             `json:"current_step"`
	CompensationState         string             `json:"compensation_state"`
	ExpectedIamVersion        pgtype.Int8        `json:"expected_iam_version"`
	ResultingIamVersion       pgtype.Int8        `json:"resulting_iam_version"`
	PreviousDepartmentID      pgtype.Int8        `json:"previous_department_id"`
	PreviousMembershipVersion pgtype.Int8        `json:"previous_membership_version"`
	AppliedDepartmentID       pgtype.Int8        `json:"applied_department_id"`
	AppliedMembershipVersion  pgtype.Int8        `json:"applied_membership_version"`
	Result                    []byte             `json:"result"`
	LastErrorCode             pgtype.Text        `json:"last_error_code"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	AttemptCount              int32              `json:"attempt_count"`
	NextRetryAt               pgtype.Timestamptz `json:"next_retry_at"`
	ClientInputDeadlineAt     pgtype.Timestamptz `json:"client_input_deadline_at"`
	RetryDeadlineAt           pgtype.Timestamptz `json:"retry_deadline_at"`
	LeaseOwner                pgtype.Text        `json:"lease_owner"`
	LeasedUntil               pgtype.Timestamptz `json:"leased_until"`
	ClaimToken                pgtype.UUID        `json:"claim_token"`
	CompletedAt               pgtype.Timestamptz `json:"completed_at"`
	CommandFingerprint        pgtype.Text        `json:"command_fingerprint"`
	CompensationAttemptCount  int32              `json:"compensation_attempt_count"`
}

type AdminWorkflowRecoveryAction struct {
	ActionID            pgtype.UUID        `json:"action_id"`
	OperationID         pgtype.UUID        `json:"operation_id"`
	RecoveryPrincipalID string             `json:"recovery_principal_id"`
	AuthorizationSource string             `json:"authorization_source"`
	ApprovalID          pgtype.Text        `json:"approval_id"`
	ActionType          string             `json:"action_type"`
	ReasonCode          string             `json:"reason_code"`
	PreviousState       string             `json:"previous_state"`
	ResultingState      string             `json:"resulting_state"`
	SafeResultCode      pgtype.Text        `json:"safe_result_code"`
	RequestID           pgtype.Text        `json:"request_id"`
	CorrelationID       pgtype.Text        `json:"correlation_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type AdminWorkflowSubject struct {
	OperationID               pgtype.UUID `json:"operation_id"`
	SubjectUserID             int64       `json:"subject_user_id"`
	ExpectedIamVersion        int64       `json:"expected_iam_version"`
	ResultingTombstoneVersion pgtype.Int8 `json:"resulting_tombstone_version"`
	Active                    bool        `json:"active"`
}

type CompatibilityBridgeMode struct {
	ID                      int32              `json:"id"`
	LegacyDeleteSyncEnabled bool               `json:"legacy_delete_sync_enabled"`
	Version                 int64              `json:"version"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type CompatibilityBridgeModeChange struct {
	ChangeID                        int64              `json:"change_id"`
	PrincipalID                     string             `json:"principal_id"`
	AuthorizationSource             string             `json:"authorization_source"`
	ApprovalID                      pgtype.Text        `json:"approval_id"`
	ReasonCode                      string             `json:"reason_code"`
	PreviousVersion                 int64              `json:"previous_version"`
	PreviousLegacyDeleteSyncEnabled bool               `json:"previous_legacy_delete_sync_enabled"`
	NewVersion                      int64              `json:"new_version"`
	NewLegacyDeleteSyncEnabled      bool               `json:"new_legacy_delete_sync_enabled"`
	RequestID                       pgtype.Text        `json:"request_id"`
	CorrelationID                   pgtype.Text        `json:"correlation_id"`
	ChangedAt                       pgtype.Timestamptz `json:"changed_at"`
}

type CompatibilityRolloutGate struct {
	GateID                        int64              `json:"gate_id"`
	Phase                         string             `json:"phase"`
	CapabilityManifestHash        string             `json:"capability_manifest_hash"`
	BridgeModeVersion             int64              `json:"bridge_mode_version"`
	BridgeLegacyDeleteSyncEnabled bool               `json:"bridge_legacy_delete_sync_enabled"`
	ObservationStartedAt          pgtype.Timestamptz `json:"observation_started_at"`
	ObservedThroughAt             pgtype.Timestamptz `json:"observed_through_at"`
	MonitoringGap                 bool               `json:"monitoring_gap"`
	LegacyRows                    int64              `json:"legacy_rows"`
	NewRows                       int64              `json:"new_rows"`
	RowVersionChecksum            pgtype.Text        `json:"row_version_checksum"`
	MismatchCount                 int64              `json:"mismatch_count"`
	LastMismatchAt                pgtype.Timestamptz `json:"last_mismatch_at"`
	RollbackArtifactID            pgtype.Text        `json:"rollback_artifact_id"`
	RollbackSuiteResult           pgtype.Text        `json:"rollback_suite_result"`
	ApprovingPrincipalID          string             `json:"approving_principal_id"`
	ApprovalID                    pgtype.Text        `json:"approval_id"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
}

type Department struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	ParentID  pgtype.Int8        `json:"parent_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type IamCommandReceipt struct {
	OperationID        pgtype.UUID        `json:"operation_id"`
	CommandName        string             `json:"command_name"`
	RequestFingerprint string             `json:"request_fingerprint"`
	Status             string             `json:"status"`
	SubjectID          pgtype.Int8        `json:"subject_id"`
	Result             []byte             `json:"result"`
	ErrorCode          pgtype.Text        `json:"error_code"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
}

type IamOutboxEvent struct {
	EventID           pgtype.UUID        `json:"event_id"`
	EventType         string             `json:"event_type"`
	EventVersion      int32              `json:"event_version"`
	Producer          string             `json:"producer"`
	AggregateType     string             `json:"aggregate_type"`
	AggregateID       string             `json:"aggregate_id"`
	AggregateVersion  int64              `json:"aggregate_version"`
	Payload           []byte             `json:"payload"`
	CorrelationID     string             `json:"correlation_id"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
	Status            string             `json:"status"`
	AvailableAt       pgtype.Timestamptz `json:"available_at"`
	DeliveryEpoch     int32              `json:"delivery_epoch"`
	EpochStartedAt    pgtype.Timestamptz `json:"epoch_started_at"`
	AttemptCount      int32              `json:"attempt_count"`
	TotalAttemptCount int64              `json:"total_attempt_count"`
	LeaseOwner        pgtype.Text        `json:"lease_owner"`
	LeasedUntil       pgtype.Timestamptz `json:"leased_until"`
	ClaimToken        pgtype.UUID        `json:"claim_token"`
	LastErrorCode     pgtype.Text        `json:"last_error_code"`
	BlockedAt         pgtype.Timestamptz `json:"blocked_at"`
	BlockedReasonCode pgtype.Text        `json:"blocked_reason_code"`
	PublishedAt       pgtype.Timestamptz `json:"published_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type IamOutboxMetric struct {
	MetricKey string `json:"metric_key"`
	Count     int64  `json:"count"`
}

type IamOutboxRequeue struct {
	EventID                 pgtype.UUID        `json:"event_id"`
	DeliveryEpoch           int32              `json:"delivery_epoch"`
	RecoveryPrincipalID     string             `json:"recovery_principal_id"`
	ReasonCode              string             `json:"reason_code"`
	PreviousEpochStartedAt  pgtype.Timestamptz `json:"previous_epoch_started_at"`
	PreviousEpochDeadlineAt pgtype.Timestamptz `json:"previous_epoch_deadline_at"`
	PreviousBlockedAt       pgtype.Timestamptz `json:"previous_blocked_at"`
	PreviousBlockedReason   pgtype.Text        `json:"previous_blocked_reason"`
	PreviousLastErrorCode   pgtype.Text        `json:"previous_last_error_code"`
	PreviousEpochAttempts   pgtype.Int4        `json:"previous_epoch_attempts"`
	PreviousTotalAttempts   pgtype.Int8        `json:"previous_total_attempts"`
	AuthorizationSource     pgtype.Text        `json:"authorization_source"`
	ApprovalID              pgtype.Text        `json:"approval_id"`
	RequestID               pgtype.Text        `json:"request_id"`
	CorrelationID           pgtype.Text        `json:"correlation_id"`
	RequeuedAt              pgtype.Timestamptz `json:"requeued_at"`
}

type OrganizationCommandReceipt struct {
	OperationID                pgtype.UUID        `json:"operation_id"`
	CommandName                string             `json:"command_name"`
	RequestFingerprint         string             `json:"request_fingerprint"`
	Status                     string             `json:"status"`
	SubjectID                  pgtype.Int8        `json:"subject_id"`
	Result                     []byte             `json:"result"`
	ErrorCode                  pgtype.Text        `json:"error_code"`
	PreviousDepartmentID       pgtype.Int8        `json:"previous_department_id"`
	PreviousMembershipVersion  pgtype.Int8        `json:"previous_membership_version"`
	ResultingDepartmentID      pgtype.Int8        `json:"resulting_department_id"`
	ResultingMembershipVersion pgtype.Int8        `json:"resulting_membership_version"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	CompletedAt                pgtype.Timestamptz `json:"completed_at"`
}

type OrganizationInboxMessage struct {
	EventID          pgtype.UUID        `json:"event_id"`
	HandlerName      string             `json:"handler_name"`
	EventType        string             `json:"event_type"`
	EventVersion     int32              `json:"event_version"`
	AggregateID      string             `json:"aggregate_id"`
	AggregateVersion int64              `json:"aggregate_version"`
	ReceivedAt       pgtype.Timestamptz `json:"received_at"`
	ProcessedAt      pgtype.Timestamptz `json:"processed_at"`
}

type OrganizationInboxMetric struct {
	MetricKey string `json:"metric_key"`
	Count     int64  `json:"count"`
}

type OrganizationUserDepartment struct {
	UserID            int64              `json:"user_id"`
	DepartmentID      pgtype.Int8        `json:"department_id"`
	MembershipVersion int64              `json:"membership_version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Permission struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PlatformEvidenceCleanupAudit struct {
	AuditID             pgtype.UUID        `json:"audit_id"`
	ApprovalID          string             `json:"approval_id"`
	PrincipalID         string             `json:"principal_id"`
	AuthorizationSource string             `json:"authorization_source"`
	RequestID           pgtype.Text        `json:"request_id"`
	CorrelationID       pgtype.Text        `json:"correlation_id"`
	RequestedCutoff     pgtype.Timestamptz `json:"requested_cutoff"`
	EffectiveCutoff     pgtype.Timestamptz `json:"effective_cutoff"`
	DryRunCounts        []byte             `json:"dry_run_counts"`
	Status              string             `json:"status"`
	PurgedCounts        []byte             `json:"purged_counts"`
	BlockedReason       pgtype.Text        `json:"blocked_reason"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	FinalizedAt         pgtype.Timestamptz `json:"finalized_at"`
}

type Role struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Code      string             `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

type Session struct {
	ID         int64              `json:"id"`
	TokenHash  string             `json:"token_hash"`
	UserID     int64              `json:"user_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type User struct {
	ID             int64              `json:"id"`
	Username       string             `json:"username"`
	PasswordHash   string             `json:"password_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Account        pgtype.Text        `json:"account"`
	Email          pgtype.Text        `json:"email"`
	DepartmentID   pgtype.Int8        `json:"department_id"`
	LifecycleState string             `json:"lifecycle_state"`
	Version        int64              `json:"version"`
}

type UserRole struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}
