// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// One bounded query for the current list page; users without a state row are
	// simply absent from the result (the BFF maps absence to no-department).
	BatchGetUserMemberships(ctx context.Context, dollar_1 []int64) ([]BatchGetUserMembershipsRow, error)
	CountDepartmentsByParentID(ctx context.Context, parentID pgtype.Int8) (int64, error)
	// evidence_cleanup.sql
	// Organization owner-local evidence cleanup (data-model.md "Retention and
	// cleanup matrix", T078). Organization evidence is always terminal: receipts
	// are written in the succeeded/rejected state only (schema CHECK) and inbox
	// dedupe rows exist only after successful processing — so there is no
	// unresolved Organization evidence to block a purge. The inbox minimum is
	// "at least as long as the producer outbox can be replayed"; the 30-day
	// processing floor plus the Platform coordinator's most-conservative-cutoff
	// cross-owner agreement uphold that without any cross-owner SQL.
	CountEligibleCommandReceipts(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error)
	CountEligibleInboxMessages(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error)
	// Delete protection counts Organization-owned memberships (data-model.md:
	// Organization SQL must not read the IAM users table). The bridge keeps these
	// state rows 1:1 with users during the compatibility window.
	CountUsersByDepartmentID(ctx context.Context, departmentID pgtype.Int8) (int64, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	// First state row: real department (set) or null tombstone (clear).
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (OrganizationUserDepartment, error)
	DeleteDepartment(ctx context.Context, id int64) error
	// inbox.sql
	// Terminal IAM user-deleted consumption (US2, contracts/organization-application.md).
	// The service deletes the membership state rows and inserts the successful
	// dedupe row in one Organization transaction; a handler failure rolls both
	// back. Never references IAM tables.
	// Full-batch physical cleanup (terminal deletion path); absent rows are a
	// normal no-op.
	DeleteMembershipsForUsers(ctx context.Context, dollar_1 []int64) error
	GetCommandReceipt(ctx context.Context, arg GetCommandReceiptParams) (GetCommandReceiptRow, error)
	GetDepartmentByID(ctx context.Context, id int64) (Department, error)
	GetDepartmentByName(ctx context.Context, name string) (Department, error)
	// Dedupe check for (event_id, handler_name). Missing = not yet processed.
	GetInboxMessage(ctx context.Context, arg GetInboxMessageParams) (OrganizationInboxMessage, error)
	// Read the Organization-owned cumulative inbox counters (T066 table) for
	// metrics exposition (T074). Key-value rows; absent keys simply don't exist.
	GetInboxMetrics(ctx context.Context) ([]OrganizationInboxMetric, error)
	// memberships.sql
	// Read-side queries for organization_user_departments (US1 BFF composition;
	// the full versioned membership mutations land with US2/T035-T036).
	// All references stay inside Organization-owned tables (ownership matrix T016):
	// organization_user_departments + departments only — never IAM tables.
	// Missing row means "Organization state never established" (normal empty
	// result for the BFF, not an error). The department name is joined so the
	// profile composition needs no per-row lookup.
	GetUserMembershipByUserID(ctx context.Context, userID int64) (GetUserMembershipByUserIDRow, error)
	// Cumulative inbox observability counter (T066): processed / duplicates /
	// handler-failure outcomes. Atomic delta upsert on the Organization-owned
	// metrics table; never affects handler semantics.
	IncrementInboxMetric(ctx context.Context, arg IncrementInboxMetricParams) error
	// Successful-processing evidence; ON CONFLICT DO NOTHING is belt-and-braces
	// for a racing redelivery, never an overwrite.
	InsertInboxMessage(ctx context.Context, arg InsertInboxMessageParams) error
	// departments.sql
	// Queries for the departments table (self-referencing tree).
	ListDepartments(ctx context.Context) ([]Department, error)
	// Complete deterministic candidate-id set for the department filter; the IAM
	// side applies its own filters and pagination over these ids.
	ListUserIDsByDepartment(ctx context.Context, departmentID pgtype.Int8) ([]int64, error)
	// memberships_mutations.sql
	// Versioned membership mutations (US2, contracts/organization-application.md).
	// The service serializes each mutation inside one Organization-local
	// transaction: lock the state row FOR UPDATE, decide against the expected
	// version, then create/update. All references stay inside Organization-owned
	// tables (ownership matrix T016) — never IAM tables.
	// Row-level lock for CAS decision-making. Missing row = no state established
	// (a normal empty result for the decision, not an error).
	LockMembershipByUserID(ctx context.Context, userID int64) (OrganizationUserDepartment, error)
	// The earliest retained Organization terminal timestamps (oldest receipt
	// completion and oldest inbox processing, each NULL when absent). The adapter
	// computes the replay floor as min(these) + 30 days — the earliest cutoff at
	// which any Organization evidence becomes eligible.
	OldestReplayableEvidenceAt(ctx context.Context) (OldestReplayableEvidenceAtRow, error)
	PurgeEligibleCommandReceipts(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error)
	PurgeEligibleInboxMessages(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error)
	// receipts.sql
	// Owner-local command evidence (US2, contracts/organization-application.md).
	// The service commits the receipt in the same Organization transaction as the
	// side effect; a resolved receipt replays the committed result after
	// timeout/crash. Never references IAM tables.
	// SaveCommandReceipt is only reached through resolve-first (no receipt yet),
	// so a conflict is unreachable; DO NOTHING is belt-and-braces against
	// corrupting committed evidence.
	SaveCommandReceipt(ctx context.Context, arg SaveCommandReceiptParams) error
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error)
	// Version-bearing replacement under the service's CAS decision (the row is
	// locked first; the WHERE is defense in depth, not the decision point).
	UpdateMembership(ctx context.Context, arg UpdateMembershipParams) (OrganizationUserDepartment, error)
}

var _ Querier = (*Queries)(nil)
