// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCommandReceipt = `-- name: GetCommandReceipt :one
SELECT operation_id, command_name, request_fingerprint, status, subject_id,
       previous_department_id, previous_membership_version,
       resulting_department_id, resulting_membership_version, error_code,
       created_at, completed_at
FROM organization_command_receipts
WHERE operation_id = $1 AND command_name = $2
`

type GetCommandReceiptParams struct {
	OperationID pgtype.UUID `json:"operation_id"`
	CommandName string      `json:"command_name"`
}

type GetCommandReceiptRow struct {
	OperationID                pgtype.UUID        `json:"operation_id"`
	CommandName                string             `json:"command_name"`
	RequestFingerprint         string             `json:"request_fingerprint"`
	Status                     string             `json:"status"`
	SubjectID                  pgtype.Int8        `json:"subject_id"`
	PreviousDepartmentID       pgtype.Int8        `json:"previous_department_id"`
	PreviousMembershipVersion  pgtype.Int8        `json:"previous_membership_version"`
	ResultingDepartmentID      pgtype.Int8        `json:"resulting_department_id"`
	ResultingMembershipVersion pgtype.Int8        `json:"resulting_membership_version"`
	ErrorCode                  pgtype.Text        `json:"error_code"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	CompletedAt                pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) GetCommandReceipt(ctx context.Context, arg GetCommandReceiptParams) (GetCommandReceiptRow, error) {
	row := q.db.QueryRow(ctx, getCommandReceipt, arg.OperationID, arg.CommandName)
	var i GetCommandReceiptRow
	err := row.Scan(
		&i.OperationID,
		&i.CommandName,
		&i.RequestFingerprint,
		&i.Status,
		&i.SubjectID,
		&i.PreviousDepartmentID,
		&i.PreviousMembershipVersion,
		&i.ResultingDepartmentID,
		&i.ResultingMembershipVersion,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const saveCommandReceipt = `-- name: SaveCommandReceipt :exec

INSERT INTO organization_command_receipts (
    operation_id, command_name, request_fingerprint, status, subject_id,
    previous_department_id, previous_membership_version,
    resulting_department_id, resulting_membership_version, error_code,
    completed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
ON CONFLICT (operation_id, command_name) DO NOTHING
`

type SaveCommandReceiptParams struct {
	OperationID                pgtype.UUID `json:"operation_id"`
	CommandName                string      `json:"command_name"`
	RequestFingerprint         string      `json:"request_fingerprint"`
	Status                     string      `json:"status"`
	SubjectID                  pgtype.Int8 `json:"subject_id"`
	PreviousDepartmentID       pgtype.Int8 `json:"previous_department_id"`
	PreviousMembershipVersion  pgtype.Int8 `json:"previous_membership_version"`
	ResultingDepartmentID      pgtype.Int8 `json:"resulting_department_id"`
	ResultingMembershipVersion pgtype.Int8 `json:"resulting_membership_version"`
	ErrorCode                  pgtype.Text `json:"error_code"`
}

// receipts.sql
// Owner-local command evidence (US2, contracts/organization-application.md).
// The service commits the receipt in the same Organization transaction as the
// side effect; a resolved receipt replays the committed result after
// timeout/crash. Never references IAM tables.
// SaveCommandReceipt is only reached through resolve-first (no receipt yet),
// so a conflict is unreachable; DO NOTHING is belt-and-braces against
// corrupting committed evidence.
func (q *Queries) SaveCommandReceipt(ctx context.Context, arg SaveCommandReceiptParams) error {
	_, err := q.db.Exec(ctx, saveCommandReceipt,
		arg.OperationID,
		arg.CommandName,
		arg.RequestFingerprint,
		arg.Status,
		arg.SubjectID,
		arg.PreviousDepartmentID,
		arg.PreviousMembershipVersion,
		arg.ResultingDepartmentID,
		arg.ResultingMembershipVersion,
		arg.ErrorCode,
	)
	return err
}
