// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence_cleanup.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEligibleCommandReceipts = `-- name: CountEligibleCommandReceipts :one
SELECT count(*) FROM iam_command_receipts
WHERE status IN ('succeeded', 'rejected')
  AND completed_at <= $1::timestamptz - interval '30 days'
`

func (q *Queries) CountEligibleCommandReceipts(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countEligibleCommandReceipts, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEligibleOutboxRequeues = `-- name: CountEligibleOutboxRequeues :one
SELECT count(*) FROM iam_outbox_requeues r
JOIN iam_outbox_events e USING (event_id)
WHERE e.status = 'published'
  AND e.published_at <= $1::timestamptz - interval '30 days'
  AND r.requeued_at <= $1::timestamptz - interval '30 days'
`

func (q *Queries) CountEligibleOutboxRequeues(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countEligibleOutboxRequeues, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEligiblePublishedOutboxEvents = `-- name: CountEligiblePublishedOutboxEvents :one
SELECT count(*) FROM iam_outbox_events e
WHERE e.status = 'published'
  AND e.published_at <= $1::timestamptz - interval '30 days'
  AND NOT EXISTS (
      SELECT 1 FROM iam_outbox_requeues r
      WHERE r.event_id = e.event_id
        AND r.requeued_at > $1::timestamptz - interval '30 days')
`

// A published event is eligible only when it is also past the last-requeue
// retention: any requeue row younger than 30 days keeps the event (and all of
// its requeues) protected.
func (q *Queries) CountEligiblePublishedOutboxEvents(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countEligiblePublishedOutboxEvents, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnresolvedOutboxEvents = `-- name: CountUnresolvedOutboxEvents :one

SELECT count(*) FROM iam_outbox_events
WHERE status IN ('pending', 'leased', 'blocked')
`

// evidence_cleanup.sql
// IAM owner-local evidence cleanup (data-model.md "Retention and cleanup
// matrix", T078). Every predicate is conservative: rows are eligible only 30
// calendar days after their terminal timestamp, published outbox rows are
// held until 30 days after publish AND 30 days after the last requeue
// (whichever is later), and nothing is ever deleted while any outbox event is
// pending/leased/blocked. All timestamps are explicit; the caller's cutoff
// drives the predicates row-by-row, so a too-early cutoff simply matches
// nothing.
func (q *Queries) CountUnresolvedOutboxEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnresolvedOutboxEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const oldestReplayableEvidenceAt = `-- name: OldestReplayableEvidenceAt :one
SELECT
    (SELECT min(completed_at)::timestamptz FROM iam_command_receipts
      WHERE status IN ('succeeded', 'rejected')) AS oldest_receipt_completed_at,
    (SELECT min(published_at)::timestamptz FROM iam_outbox_events
      WHERE status = 'published') AS oldest_published_at
`

type OldestReplayableEvidenceAtRow struct {
	OldestReceiptCompletedAt pgtype.Timestamptz `json:"oldest_receipt_completed_at"`
	OldestPublishedAt        pgtype.Timestamptz `json:"oldest_published_at"`
}

// The earliest retained IAM terminal timestamps (oldest receipt completion and
// oldest publish, each NULL when absent). The adapter computes the replay
// floor as min(these) + 30 days — the earliest cutoff at which any IAM
// evidence becomes eligible. Requeues are covered by their event's
// published_at (requeued_at < final published_at for a published event), so
// only receipts and published events contribute to the floor.
func (q *Queries) OldestReplayableEvidenceAt(ctx context.Context) (OldestReplayableEvidenceAtRow, error) {
	row := q.db.QueryRow(ctx, oldestReplayableEvidenceAt)
	var i OldestReplayableEvidenceAtRow
	err := row.Scan(&i.OldestReceiptCompletedAt, &i.OldestPublishedAt)
	return i, err
}

const purgeEligibleCommandReceipts = `-- name: PurgeEligibleCommandReceipts :execrows
DELETE FROM iam_command_receipts
WHERE status IN ('succeeded', 'rejected')
  AND completed_at <= $1::timestamptz - interval '30 days'
`

func (q *Queries) PurgeEligibleCommandReceipts(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeEligibleCommandReceipts, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeEligibleOutboxRequeues = `-- name: PurgeEligibleOutboxRequeues :execrows
DELETE FROM iam_outbox_requeues r
USING iam_outbox_events e
WHERE r.event_id = e.event_id
  AND e.status = 'published'
  AND e.published_at <= $1::timestamptz - interval '30 days'
  AND r.requeued_at <= $1::timestamptz - interval '30 days'
`

// Requeues go first so the FK into iam_outbox_events never blocks the event
// deletion below; every requeue of an eligible published event is itself
// eligible because requeued_at < final published_at.
func (q *Queries) PurgeEligibleOutboxRequeues(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeEligibleOutboxRequeues, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeEligiblePublishedOutboxEvents = `-- name: PurgeEligiblePublishedOutboxEvents :execrows
DELETE FROM iam_outbox_events e
WHERE e.status = 'published'
  AND e.published_at <= $1::timestamptz - interval '30 days'
  AND NOT EXISTS (
      SELECT 1 FROM iam_outbox_requeues r
      WHERE r.event_id = e.event_id
        AND r.requeued_at > $1::timestamptz - interval '30 days')
`

func (q *Queries) PurgeEligiblePublishedOutboxEvents(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeEligiblePublishedOutboxEvents, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
