// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ackOutboxEvent = `-- name: AckOutboxEvent :execrows
UPDATE iam_outbox_events
SET status = 'published',
    published_at = now(),
    lease_owner = NULL,
    leased_until = NULL,
    claim_token = NULL
WHERE event_id = $1
  AND status = 'leased'
  AND claim_token = $2
`

type AckOutboxEventParams struct {
	EventID    pgtype.UUID `json:"event_id"`
	ClaimToken pgtype.UUID `json:"claim_token"`
}

// Claim-token CAS to published; stale tokens match no row.
func (q *Queries) AckOutboxEvent(ctx context.Context, arg AckOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, ackOutboxEvent, arg.EventID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const blockOutboxEvent = `-- name: BlockOutboxEvent :execrows
UPDATE iam_outbox_events
SET status = 'blocked',
    blocked_at = now(),
    blocked_reason_code = $2,
    last_error_code = $2,
    lease_owner = NULL,
    leased_until = NULL,
    claim_token = NULL
WHERE event_id = $1
  AND status = 'leased'
  AND claim_token = $3
`

type BlockOutboxEventParams struct {
	EventID           pgtype.UUID `json:"event_id"`
	BlockedReasonCode pgtype.Text `json:"blocked_reason_code"`
	ClaimToken        pgtype.UUID `json:"claim_token"`
}

// Non-retryable/unsupported contract → durable blocked, claim-token CAS.
func (q *Queries) BlockOutboxEvent(ctx context.Context, arg BlockOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, blockOutboxEvent, arg.EventID, arg.BlockedReasonCode, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const blockOutboxExhausted = `-- name: BlockOutboxExhausted :execrows
UPDATE iam_outbox_events
SET status = 'blocked',
    blocked_at = now(),
    blocked_reason_code = 'delivery_exhausted',
    last_error_code = 'delivery_exhausted',
    lease_owner = NULL,
    leased_until = NULL,
    claim_token = NULL
WHERE event_id = $1
  AND status IN ('pending', 'leased')
`

// Epoch ceiling hit at claim time (attempts >= 20 or epoch_started_at + 24h
// past): atomically blocked WITHOUT a new lease and WITHOUT burning an
// attempt — no consumer call is made for it.
func (q *Queries) BlockOutboxExhausted(ctx context.Context, eventID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, blockOutboxExhausted, eventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOutboxBacklog = `-- name: GetOutboxBacklog :one
SELECT
    (SELECT count(*) FROM iam_outbox_events WHERE status = 'pending')   AS pending_count,
    (SELECT count(*) FROM iam_outbox_events WHERE status = 'leased')    AS leased_count,
    (SELECT count(*) FROM iam_outbox_events WHERE status = 'blocked')   AS blocked_count,
    (SELECT min(available_at)::timestamptz FROM iam_outbox_events WHERE status = 'pending')   AS oldest_pending_at,
    (SELECT count(*) FROM iam_outbox_events WHERE status = 'published') AS published_count,
    (SELECT min(leased_until)::timestamptz FROM iam_outbox_events WHERE status = 'leased')    AS oldest_leased_until,
    (SELECT count FROM iam_outbox_metrics WHERE metric_key = 'lease_recoveries')      AS lease_recovery_count,
    (SELECT count FROM iam_outbox_metrics WHERE metric_key = 'stale_claim_rejections') AS stale_claim_rejection_count
`

type GetOutboxBacklogRow struct {
	PendingCount             int64              `json:"pending_count"`
	LeasedCount              int64              `json:"leased_count"`
	BlockedCount             int64              `json:"blocked_count"`
	OldestPendingAt          pgtype.Timestamptz `json:"oldest_pending_at"`
	PublishedCount           int64              `json:"published_count"`
	OldestLeasedUntil        pgtype.Timestamptz `json:"oldest_leased_until"`
	LeaseRecoveryCount       int64              `json:"lease_recovery_count"`
	StaleClaimRejectionCount int64              `json:"stale_claim_rejection_count"`
}

// Required observability summary (contracts/domain-events.md §Failure and
// reconciliation): pending/leased/published/blocked counts, oldest pending
// age, oldest live lease, and the cumulative lease-recovery and stale-claim-
// rejection counters.
func (q *Queries) GetOutboxBacklog(ctx context.Context) (GetOutboxBacklogRow, error) {
	row := q.db.QueryRow(ctx, getOutboxBacklog)
	var i GetOutboxBacklogRow
	err := row.Scan(
		&i.PendingCount,
		&i.LeasedCount,
		&i.BlockedCount,
		&i.OldestPendingAt,
		&i.PublishedCount,
		&i.OldestLeasedUntil,
		&i.LeaseRecoveryCount,
		&i.StaleClaimRejectionCount,
	)
	return i, err
}

const getOutboxEventByIDForRequeue = `-- name: GetOutboxEventByIDForRequeue :one
SELECT event_id, delivery_epoch, epoch_started_at, attempt_count,
       total_attempt_count, last_error_code, blocked_at, blocked_reason_code
FROM iam_outbox_events
WHERE event_id = $1
  AND status = 'blocked'
FOR UPDATE
`

type GetOutboxEventByIDForRequeueRow struct {
	EventID           pgtype.UUID        `json:"event_id"`
	DeliveryEpoch     int32              `json:"delivery_epoch"`
	EpochStartedAt    pgtype.Timestamptz `json:"epoch_started_at"`
	AttemptCount      int32              `json:"attempt_count"`
	TotalAttemptCount int64              `json:"total_attempt_count"`
	LastErrorCode     pgtype.Text        `json:"last_error_code"`
	BlockedAt         pgtype.Timestamptz `json:"blocked_at"`
	BlockedReasonCode pgtype.Text        `json:"blocked_reason_code"`
}

// Locked blocked-row read for the requeue transaction; the caller bumps the
// epoch and appends the immutable previous-epoch evidence atomically.
func (q *Queries) GetOutboxEventByIDForRequeue(ctx context.Context, eventID pgtype.UUID) (GetOutboxEventByIDForRequeueRow, error) {
	row := q.db.QueryRow(ctx, getOutboxEventByIDForRequeue, eventID)
	var i GetOutboxEventByIDForRequeueRow
	err := row.Scan(
		&i.EventID,
		&i.DeliveryEpoch,
		&i.EpochStartedAt,
		&i.AttemptCount,
		&i.TotalAttemptCount,
		&i.LastErrorCode,
		&i.BlockedAt,
		&i.BlockedReasonCode,
	)
	return i, err
}

const incrementOutboxMetric = `-- name: IncrementOutboxMetric :exec
INSERT INTO iam_outbox_metrics(metric_key, count) VALUES ($1, $2)
ON CONFLICT (metric_key) DO UPDATE
    SET count = iam_outbox_metrics.count + EXCLUDED.count
`

type IncrementOutboxMetricParams struct {
	MetricKey string `json:"metric_key"`
	Count     int64  `json:"count"`
}

// Cumulative observability counter (T066): atomic delta upsert on the
// IAM-owned metrics table. Never affects delivery semantics.
func (q *Queries) IncrementOutboxMetric(ctx context.Context, arg IncrementOutboxMetricParams) error {
	_, err := q.db.Exec(ctx, incrementOutboxMetric, arg.MetricKey, arg.Count)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec

INSERT INTO iam_outbox_events (
    event_id, event_type, event_version, producer, aggregate_type, aggregate_id,
    aggregate_version, payload, correlation_id, occurred_at, status, available_at,
    delivery_epoch, epoch_started_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'pending', $10, 1, $10)
`

type InsertOutboxEventParams struct {
	EventID          pgtype.UUID        `json:"event_id"`
	EventType        string             `json:"event_type"`
	EventVersion     int32              `json:"event_version"`
	Producer         string             `json:"producer"`
	AggregateType    string             `json:"aggregate_type"`
	AggregateID      string             `json:"aggregate_id"`
	AggregateVersion int64              `json:"aggregate_version"`
	Payload          []byte             `json:"payload"`
	CorrelationID    string             `json:"correlation_id"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
}

// outbox.sql
// Producer-side domain event enqueue (T048 DeleteUsers, T049 compensation):
// the first real event is iam.user.deleted version 1. Rows commit in the same
// IAM transaction as their side effect — rollback removes the event too.
// Fresh pending event at delivery epoch 1, immediately available
// (available_at = occurred_at = epoch_started_at satisfies the schema CHECK).
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.EventID,
		arg.EventType,
		arg.EventVersion,
		arg.Producer,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.Payload,
		arg.CorrelationID,
		arg.OccurredAt,
	)
	return err
}

const insertOutboxRequeue = `-- name: InsertOutboxRequeue :exec
INSERT INTO iam_outbox_requeues (
    event_id, delivery_epoch, recovery_principal_id, reason_code,
    previous_epoch_started_at, previous_epoch_deadline_at, previous_blocked_at,
    previous_blocked_reason, previous_last_error_code, previous_epoch_attempts,
    previous_total_attempts, authorization_source, approval_id, request_id,
    correlation_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type InsertOutboxRequeueParams struct {
	EventID                 pgtype.UUID        `json:"event_id"`
	DeliveryEpoch           int32              `json:"delivery_epoch"`
	RecoveryPrincipalID     string             `json:"recovery_principal_id"`
	ReasonCode              string             `json:"reason_code"`
	PreviousEpochStartedAt  pgtype.Timestamptz `json:"previous_epoch_started_at"`
	PreviousEpochDeadlineAt pgtype.Timestamptz `json:"previous_epoch_deadline_at"`
	PreviousBlockedAt       pgtype.Timestamptz `json:"previous_blocked_at"`
	PreviousBlockedReason   pgtype.Text        `json:"previous_blocked_reason"`
	PreviousLastErrorCode   pgtype.Text        `json:"previous_last_error_code"`
	PreviousEpochAttempts   pgtype.Int4        `json:"previous_epoch_attempts"`
	PreviousTotalAttempts   pgtype.Int8        `json:"previous_total_attempts"`
	AuthorizationSource     pgtype.Text        `json:"authorization_source"`
	ApprovalID              pgtype.Text        `json:"approval_id"`
	RequestID               pgtype.Text        `json:"request_id"`
	CorrelationID           pgtype.Text        `json:"correlation_id"`
}

// Immutable audit row: one per resulting epoch, complete previous-epoch
// evidence + trusted recovery identity/authorization/approval/correlation.
func (q *Queries) InsertOutboxRequeue(ctx context.Context, arg InsertOutboxRequeueParams) error {
	_, err := q.db.Exec(ctx, insertOutboxRequeue,
		arg.EventID,
		arg.DeliveryEpoch,
		arg.RecoveryPrincipalID,
		arg.ReasonCode,
		arg.PreviousEpochStartedAt,
		arg.PreviousEpochDeadlineAt,
		arg.PreviousBlockedAt,
		arg.PreviousBlockedReason,
		arg.PreviousLastErrorCode,
		arg.PreviousEpochAttempts,
		arg.PreviousTotalAttempts,
		arg.AuthorizationSource,
		arg.ApprovalID,
		arg.RequestID,
		arg.CorrelationID,
	)
	return err
}

const leaseOutboxEvent = `-- name: LeaseOutboxEvent :execrows
UPDATE iam_outbox_events
SET status = 'leased',
    lease_owner = $2,
    leased_until = $3,
    claim_token = $4,
    attempt_count = attempt_count + 1,
    total_attempt_count = total_attempt_count + 1
WHERE event_id = $1
  AND status IN ('pending', 'leased')
`

type LeaseOutboxEventParams struct {
	EventID     pgtype.UUID        `json:"event_id"`
	LeaseOwner  pgtype.Text        `json:"lease_owner"`
	LeasedUntil pgtype.Timestamptz `json:"leased_until"`
	ClaimToken  pgtype.UUID        `json:"claim_token"`
}

// Atomically hand out a lease: fresh claim or expired-lease reclaim. Every
// lease counts one attempt, so a worker crash after claim already consumed
// budget. The row is locked by ListClaimableOutboxEvents; the status guard is
// defensive.
func (q *Queries) LeaseOutboxEvent(ctx context.Context, arg LeaseOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, leaseOutboxEvent,
		arg.EventID,
		arg.LeaseOwner,
		arg.LeasedUntil,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listClaimableOutboxEvents = `-- name: ListClaimableOutboxEvents :many

SELECT event_id, event_type, event_version, producer, aggregate_type, aggregate_id,
       aggregate_version, payload, correlation_id, occurred_at, status, available_at,
       delivery_epoch, epoch_started_at, attempt_count, total_attempt_count,
       lease_owner, leased_until, claim_token, last_error_code, blocked_at,
       blocked_reason_code, published_at, created_at
FROM iam_outbox_events
WHERE (status = 'pending' AND available_at <= now())
   OR (status = 'leased'  AND leased_until <= now())
ORDER BY available_at, created_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// ==========================================================================
// Delivery side (T061 OutboxDeliveryPort, contracts/domain-events.md §Outbox
// delivery state). Every transition is a single atomic statement or one short
// transaction — never read-then-write — and every ack/failure/block is a
// claim-token CAS (stale tokens match no row and are rejected).
// Eligible rows for one claim batch: pending rows whose backoff elapsed plus
// leased rows whose lease expired. Rows are locked in the caller's short
// transaction (FOR UPDATE SKIP LOCKED) so concurrent claimers skip them.
func (q *Queries) ListClaimableOutboxEvents(ctx context.Context, limit int32) ([]IamOutboxEvent, error) {
	rows, err := q.db.Query(ctx, listClaimableOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IamOutboxEvent{}
	for rows.Next() {
		var i IamOutboxEvent
		if err := rows.Scan(
			&i.EventID,
			&i.EventType,
			&i.EventVersion,
			&i.Producer,
			&i.AggregateType,
			&i.AggregateID,
			&i.AggregateVersion,
			&i.Payload,
			&i.CorrelationID,
			&i.OccurredAt,
			&i.Status,
			&i.AvailableAt,
			&i.DeliveryEpoch,
			&i.EpochStartedAt,
			&i.AttemptCount,
			&i.TotalAttemptCount,
			&i.LeaseOwner,
			&i.LeasedUntil,
			&i.ClaimToken,
			&i.LastErrorCode,
			&i.BlockedAt,
			&i.BlockedReasonCode,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordOutboxFailure = `-- name: RecordOutboxFailure :one
UPDATE iam_outbox_events
SET status = CASE
        WHEN attempt_count >= 20 OR epoch_started_at + interval '24 hours' <= now()
            THEN 'blocked'
        ELSE 'pending'
    END,
    available_at = CASE
        WHEN attempt_count >= 20 OR epoch_started_at + interval '24 hours' <= now()
            THEN epoch_started_at
        ELSE $3
    END,
    blocked_at = CASE
        WHEN attempt_count >= 20 OR epoch_started_at + interval '24 hours' <= now()
            THEN now()
        ELSE NULL
    END,
    blocked_reason_code = CASE
        WHEN attempt_count >= 20 OR epoch_started_at + interval '24 hours' <= now()
            THEN 'delivery_exhausted'
        ELSE NULL
    END,
    last_error_code = $2,
    lease_owner = NULL,
    leased_until = NULL,
    claim_token = NULL
WHERE event_id = $1
  AND status = 'leased'
  AND claim_token = $4
RETURNING status
`

type RecordOutboxFailureParams struct {
	EventID       pgtype.UUID        `json:"event_id"`
	LastErrorCode pgtype.Text        `json:"last_error_code"`
	AvailableAt   pgtype.Timestamptz `json:"available_at"`
	ClaimToken    pgtype.UUID        `json:"claim_token"`
}

// ONE statement atomically chooses pending/backoff or blocked(delivery_exhausted)
// by evaluating the already-counted attempt/time ceiling; stale tokens match
// no row. No reschedule-then-block race exists because the transition is a
// single UPDATE, and the blocked branch keeps availability = epoch start so
// the schema CHECK (available_at >= epoch_started_at) always holds.
func (q *Queries) RecordOutboxFailure(ctx context.Context, arg RecordOutboxFailureParams) (string, error) {
	row := q.db.QueryRow(ctx, recordOutboxFailure,
		arg.EventID,
		arg.LastErrorCode,
		arg.AvailableAt,
		arg.ClaimToken,
	)
	var status string
	err := row.Scan(&status)
	return status, err
}

const requeueOutboxEvent = `-- name: RequeueOutboxEvent :exec
UPDATE iam_outbox_events
SET status = 'pending',
    available_at = $2,
    delivery_epoch = delivery_epoch + 1,
    epoch_started_at = $2,
    attempt_count = 0,
    lease_owner = NULL,
    leased_until = NULL,
    claim_token = NULL,
    blocked_at = NULL,
    blocked_reason_code = NULL,
    last_error_code = NULL
WHERE event_id = $1
  AND status = 'blocked'
`

type RequeueOutboxEventParams struct {
	EventID     pgtype.UUID        `json:"event_id"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
}

// Controlled requeue: pending again at a delayed available_at, new epoch
// started at available_at, epoch attempts reset, total attempts preserved,
// blocked/lease evidence cleared.
func (q *Queries) RequeueOutboxEvent(ctx context.Context, arg RequeueOutboxEventParams) error {
	_, err := q.db.Exec(ctx, requeueOutboxEvent, arg.EventID, arg.AvailableAt)
	return err
}
