// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Claim-token CAS to published; stale tokens match no row.
	AckOutboxEvent(ctx context.Context, arg AckOutboxEventParams) (int64, error)
	// The only legal transition is provisioning -> active with an expected
	// version (iam-application.md ActivateUser); the single-statement UPDATE is
	// the atomic CAS — zero rows mean the CAS missed and the service
	// distinguishes the failure reason from the current row.
	ActivateUserCAS(ctx context.Context, arg ActivateUserCASParams) (int64, error)
	// Non-retryable/unsupported contract → durable blocked, claim-token CAS.
	BlockOutboxEvent(ctx context.Context, arg BlockOutboxEventParams) (int64, error)
	// Epoch ceiling hit at claim time (attempts >= 20 or epoch_started_at + 24h
	// past): atomically blocked WITHOUT a new lease and WITHOUT burning an
	// attempt — no consumer call is made for it.
	BlockOutboxExhausted(ctx context.Context, eventID pgtype.UUID) (int64, error)
	// Version bump for the admin bootstrap; only called inside a transaction that
	// holds the row lock, so `version = version + 1` is race-free.
	BumpUserVersion(ctx context.Context, id int64) error
	CountEligibleCommandReceipts(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error)
	CountEligibleOutboxRequeues(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error)
	// A published event is eligible only when it is also past the last-requeue
	// retention: any requeue row younger than 30 days keeps the event (and all of
	// its requeues) protected.
	CountEligiblePublishedOutboxEvents(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error)
	CountManagedUsers(ctx context.Context, arg CountManagedUsersParams) (int64, error)
	// evidence_cleanup.sql
	// IAM owner-local evidence cleanup (data-model.md "Retention and cleanup
	// matrix", T078). Every predicate is conservative: rows are eligible only 30
	// calendar days after their terminal timestamp, published outbox rows are
	// held until 30 days after publish AND 30 days after the last requeue
	// (whichever is later), and nothing is ever deleted while any outbox event is
	// pending/leased/blocked. All timestamps are explicit; the caller's cutoff
	// drives the predicates row-by-row, so a too-early cutoff simply matches
	// nothing.
	CountUnresolvedOutboxEvents(ctx context.Context) (int64, error)
	CountUserRolesByRoleID(ctx context.Context, roleID int64) (int64, error)
	CountUsersByDepartment(ctx context.Context, arg CountUsersByDepartmentParams) (int64, error)
	// Provisioning identity (US3, iam-application.md CreateProvisioningUser): the
	// password hash commits with the row; lifecycle_state/version are explicit
	// ('provisioning', 1) because 000006 dropped the temporary defaults.
	CreateProvisioningUser(ctx context.Context, arg CreateProvisioningUserParams) (CreateProvisioningUserRow, error)
	// users_rbac.sql
	// User-management queries: create/update/delete users, paginated listing,
	// and the user<->role join. Query names avoid colliding with the existing
	// auth-focused CreateUser / GetUserByUsername / GetUserByID.
	// 000006 dropped the temporary lifecycle defaults; admin-created users state
	// active explicitly and create version 1 (data-model.md User invariants).
	CreateRbacUser(ctx context.Context, arg CreateRbacUserParams) (CreateRbacUserRow, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// 000006 dropped the temporary lifecycle defaults; registration states active
	// explicitly and creates version 1 (data-model.md User invariants).
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// CompensateProvisioningUser (iam-application.md CompensateProvisioningUser):
	// the single-statement CAS deletes only a still-provisioning subject at the
	// expected version — active/disabled/newer-version rows miss and escalate to
	// reconciliation. sessions/user_roles cascade away; the tombstone version is
	// the deleted prior version + 1.
	DeleteProvisioningUserCAS(ctx context.Context, arg DeleteProvisioningUserCASParams) (int64, error)
	DeleteRole(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserRolesByUserID(ctx context.Context, userID int64) error
	// DisableUser (iam-application.md DisableUser): the only legal transition is
	// active -> disabled with an expected version — provisioning subjects are
	// handled by CompensateProvisioningUser, re-enable is out of scope. Zero rows
	// mean the CAS missed and the service classifies the failure from the current
	// row.
	DisableUserCAS(ctx context.Context, arg DisableUserCASParams) (int64, error)
	GetCommandReceipt(ctx context.Context, arg GetCommandReceiptParams) (IamCommandReceipt, error)
	// Required observability summary (contracts/domain-events.md §Failure and
	// reconciliation): pending/leased/published/blocked counts, oldest pending
	// age, oldest live lease, and the cumulative lease-recovery and stale-claim-
	// rejection counters.
	GetOutboxBacklog(ctx context.Context) (GetOutboxBacklogRow, error)
	// Locked blocked-row read for the requeue transaction; the caller bumps the
	// epoch and appends the immutable previous-epoch evidence atomically.
	GetOutboxEventByIDForRequeue(ctx context.Context, eventID pgtype.UUID) (GetOutboxEventByIDForRequeueRow, error)
	// Metrics snapshot (T074): how many identities are still in the
	// provisioning lifecycle state and when the oldest one was created.
	GetProvisioningSnapshot(ctx context.Context) (GetProvisioningSnapshotRow, error)
	GetRoleByCode(ctx context.Context, code string) (Role, error)
	GetRoleByID(ctx context.Context, id int64) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	// Session lookup for Authenticate: joins the owner's username and lifecycle
	// state so the service can enforce the active-user check alongside the
	// revocation/expiry checks; s.id is the stable session reference shared with
	// Register/Login. (GetSessionByTokenHash above stays untouched for the legacy
	// services.)
	GetSessionWithUserState(ctx context.Context, tokenHash string) (GetSessionWithUserStateRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	// DeleteUsers full-batch precheck (iam-application.md DeleteUsers): locks each
	// target row until the deletion transaction commits, so validation and the
	// DELETE cannot race a concurrent update (version drift) or a concurrent
	// delete (row vanishing mid-batch). Password hash is deliberately NOT selected
	// — deletion never touches credentials (least privilege).
	GetUserByIDForUpdate(ctx context.Context, id int64) (GetUserByIDForUpdateRow, error)
	// Full identity aggregate for GetIdentity / GetAuthorizationProfile.
	GetUserByIDFull(ctx context.Context, id int64) (GetUserByIDFullRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	// IAM authentication lookup: the credentials plus lifecycle state needed by
	// Login's uniform-failure checks. (The shared GetUserByUsername above predates
	// the lifecycle columns and is left untouched for the legacy services.)
	GetUserByUsernameAuth(ctx context.Context, username string) (GetUserByUsernameAuthRow, error)
	// Admin-bootstrap lookup (GrantBuiltInAdminRole): locks the latest user row
	// for the duration of the granting transaction so concurrent grants cannot
	// race the version bump. Password hash is deliberately NOT selected — the
	// bootstrap never touches credentials (least privilege).
	GetUserByUsernameForUpdate(ctx context.Context, username string) (GetUserByUsernameForUpdateRow, error)
	GetUserFullByID(ctx context.Context, id int64) (GetUserFullByIDRow, error)
	HasPermissionByUserID(ctx context.Context, arg HasPermissionByUserIDParams) (bool, error)
	// Cumulative observability counter (T066): atomic delta upsert on the
	// IAM-owned metrics table. Never affects delivery semantics.
	IncrementOutboxMetric(ctx context.Context, arg IncrementOutboxMetricParams) error
	// outbox.sql
	// Producer-side domain event enqueue (T048 DeleteUsers, T049 compensation):
	// the first real event is iam.user.deleted version 1. Rows commit in the same
	// IAM transaction as their side effect — rollback removes the event too.
	// Fresh pending event at delivery epoch 1, immediately available
	// (available_at = occurred_at = epoch_started_at satisfies the schema CHECK).
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	// Immutable audit row: one per resulting epoch, complete previous-epoch
	// evidence + trusted recovery identity/authorization/approval/correlation.
	InsertOutboxRequeue(ctx context.Context, arg InsertOutboxRequeueParams) error
	InsertUserRole(ctx context.Context, arg InsertUserRoleParams) error
	// Atomically hand out a lease: fresh claim or expired-lease reclaim. Every
	// lease counts one attempt, so a worker crash after claim already consumed
	// budget. The row is locked by ListClaimableOutboxEvents; the status guard is
	// defensive.
	LeaseOutboxEvent(ctx context.Context, arg LeaseOutboxEventParams) (int64, error)
	// ==========================================================================
	// Delivery side (T061 OutboxDeliveryPort, contracts/domain-events.md §Outbox
	// delivery state). Every transition is a single atomic statement or one short
	// transaction — never read-then-write — and every ack/failure/block is a
	// claim-token CAS (stale tokens match no row and are rejected).
	// Eligible rows for one claim batch: pending rows whose backoff elapsed plus
	// leased rows whose lease expired. Rows are locked in the caller's short
	// transaction (FOR UPDATE SKIP LOCKED) so concurrent claimers skip them.
	ListClaimableOutboxEvents(ctx context.Context, limit int32) ([]IamOutboxEvent, error)
	// permissions.sql
	// Effective permissions are the distinct union of grants from all user roles.
	ListEffectivePermissionsByUserID(ctx context.Context, userID int64) ([]string, error)
	// Managed-user listing (BatchGetManagedIdentities): provisioning users are
	// excluded; a NULL candidate array means no id filter; empty candidate arrays
	// are short-circuited by the service before reaching the store.
	ListManagedUsers(ctx context.Context, arg ListManagedUsersParams) ([]ListManagedUsersRow, error)
	// roles.sql
	// Queries for the roles table. `code` is reserved for phase-2 permission filtering.
	ListRoles(ctx context.Context) ([]Role, error)
	ListRolesByUserID(ctx context.Context, userID int64) ([]ListRolesByUserIDRow, error)
	// Aggregated role projection for a user batch (BatchGetManagedIdentities):
	// one bounded query instead of per-row role lookups.
	ListUserRolesByUserIDs(ctx context.Context, dollar_1 []int64) ([]ListUserRolesByUserIDsRow, error)
	ListUsersByDepartment(ctx context.Context, arg ListUsersByDepartmentParams) ([]ListUsersByDepartmentRow, error)
	// The earliest retained IAM terminal timestamps (oldest receipt completion and
	// oldest publish, each NULL when absent). The adapter computes the replay
	// floor as min(these) + 30 days — the earliest cutoff at which any IAM
	// evidence becomes eligible. Requeues are covered by their event's
	// published_at (requeued_at < final published_at for a published event), so
	// only receipts and published events contribute to the floor.
	OldestReplayableEvidenceAt(ctx context.Context) (OldestReplayableEvidenceAtRow, error)
	PurgeEligibleCommandReceipts(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error)
	// Requeues go first so the FK into iam_outbox_events never blocks the event
	// deletion below; every requeue of an eligible published event is itself
	// eligible because requeued_at < final published_at.
	PurgeEligibleOutboxRequeues(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error)
	PurgeEligiblePublishedOutboxEvents(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error)
	// ONE statement atomically chooses pending/backoff or blocked(delivery_exhausted)
	// by evaluating the already-counted attempt/time ceiling; stale tokens match
	// no row. No reschedule-then-block race exists because the transition is a
	// single UPDATE, and the blocked branch keeps availability = epoch start so
	// the schema CHECK (available_at >= epoch_started_at) always holds.
	RecordOutboxFailure(ctx context.Context, arg RecordOutboxFailureParams) (string, error)
	// Controlled requeue: pending again at a delayed available_at, new epoch
	// started at available_at, epoch attempts reset, total attempts preserved,
	// blocked/lease evidence cleared.
	RequeueOutboxEvent(ctx context.Context, arg RequeueOutboxEventParams) error
	RevokeSessionByTokenHash(ctx context.Context, tokenHash string) error
	// DisableUser session revocation: every live session of the disabled subject
	// is revoked inside the same transaction as the lifecycle CAS.
	RevokeSessionsByUserID(ctx context.Context, userID int64) error
	// receipts.sql
	// IAM owner-local command evidence (US3, contracts/consistency-and-compensation.md).
	// The service commits the receipt in the same IAM transaction as the side
	// effect; a resolved receipt replays the committed result after timeout/crash.
	// result holds transport-neutral safe values only — never credentials.
	// Never references Organization or BFF tables.
	// Only reached through resolve-first (no receipt yet), so a conflict is
	// unreachable; DO NOTHING is belt-and-braces against corrupting committed
	// evidence.
	SaveCommandReceipt(ctx context.Context, arg SaveCommandReceiptParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	// Managed-user profile update (iam-application.md UpdateManagedUser): the
	// statement is the expected-version CAS AND the profile mutation — zero rows
	// mean the CAS missed and the service classifies the failure from the current
	// row. account/email take the request value verbatim (absent -> NULL); the
	// unique username constraint surfaces as a unique violation, never a miss.
	// Role replacement and the optional credential change follow in the same
	// transaction: this UPDATE locks the row until commit, so the password
	// statement below cannot interleave with a concurrent updater.
	UpdateManagedUserCAS(ctx context.Context, arg UpdateManagedUserCASParams) (int64, error)
	UpdateRbacUser(ctx context.Context, arg UpdateRbacUserParams) (UpdateRbacUserRow, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Replaces the stored hash; called only inside the transaction whose
	// UpdateManagedUserCAS already locked the row (blank/absent password simply
	// never calls this — the existing hash is preserved by omission).
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error
}

var _ Querier = (*Queries)(nil)
