// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCommandReceipt = `-- name: GetCommandReceipt :one
SELECT operation_id, command_name, request_fingerprint, status, subject_id,
       result, error_code, created_at, completed_at
FROM iam_command_receipts
WHERE operation_id = $1 AND command_name = $2
`

type GetCommandReceiptParams struct {
	OperationID pgtype.UUID `json:"operation_id"`
	CommandName string      `json:"command_name"`
}

func (q *Queries) GetCommandReceipt(ctx context.Context, arg GetCommandReceiptParams) (IamCommandReceipt, error) {
	row := q.db.QueryRow(ctx, getCommandReceipt, arg.OperationID, arg.CommandName)
	var i IamCommandReceipt
	err := row.Scan(
		&i.OperationID,
		&i.CommandName,
		&i.RequestFingerprint,
		&i.Status,
		&i.SubjectID,
		&i.Result,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const saveCommandReceipt = `-- name: SaveCommandReceipt :exec

INSERT INTO iam_command_receipts (
    operation_id, command_name, request_fingerprint, status, subject_id,
    result, error_code, completed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
ON CONFLICT (operation_id, command_name) DO NOTHING
`

type SaveCommandReceiptParams struct {
	OperationID        pgtype.UUID `json:"operation_id"`
	CommandName        string      `json:"command_name"`
	RequestFingerprint string      `json:"request_fingerprint"`
	Status             string      `json:"status"`
	SubjectID          pgtype.Int8 `json:"subject_id"`
	Result             []byte      `json:"result"`
	ErrorCode          pgtype.Text `json:"error_code"`
}

// receipts.sql
// IAM owner-local command evidence (US3, contracts/consistency-and-compensation.md).
// The service commits the receipt in the same IAM transaction as the side
// effect; a resolved receipt replays the committed result after timeout/crash.
// result holds transport-neutral safe values only — never credentials.
// Never references Organization or BFF tables.
// Only reached through resolve-first (no receipt yet), so a conflict is
// unreachable; DO NOTHING is belt-and-braces against corrupting committed
// evidence.
func (q *Queries) SaveCommandReceipt(ctx context.Context, arg SaveCommandReceiptParams) error {
	_, err := q.db.Exec(ctx, saveCommandReceipt,
		arg.OperationID,
		arg.CommandName,
		arg.RequestFingerprint,
		arg.Status,
		arg.SubjectID,
		arg.Result,
		arg.ErrorCode,
	)
	return err
}
