// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, token_hash, user_id, created_at, expires_at, revoked_at, last_used_at
`

type CreateSessionParams struct {
	TokenHash string             `json:"token_hash"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.token_hash, s.user_id, s.created_at, s.expires_at, s.revoked_at, s.last_used_at,
       u.username AS user_username, u.created_at AS user_created_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
`

type GetSessionByTokenHashRow struct {
	ID            int64              `json:"id"`
	TokenHash     string             `json:"token_hash"`
	UserID        int64              `json:"user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	UserUsername  string             `json:"user_username"`
	UserCreatedAt pgtype.Timestamptz `json:"user_created_at"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.UserUsername,
		&i.UserCreatedAt,
	)
	return i, err
}

const getSessionWithUserState = `-- name: GetSessionWithUserState :one
SELECT s.id AS session_id, s.token_hash, s.user_id, s.created_at, s.expires_at, s.revoked_at,
       u.username AS user_username, u.lifecycle_state AS user_lifecycle_state
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
`

type GetSessionWithUserStateRow struct {
	SessionID          int64              `json:"session_id"`
	TokenHash          string             `json:"token_hash"`
	UserID             int64              `json:"user_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
	UserUsername       string             `json:"user_username"`
	UserLifecycleState string             `json:"user_lifecycle_state"`
}

// Session lookup for Authenticate: joins the owner's username and lifecycle
// state so the service can enforce the active-user check alongside the
// revocation/expiry checks; s.id is the stable session reference shared with
// Register/Login. (GetSessionByTokenHash above stays untouched for the legacy
// services.)
func (q *Queries) GetSessionWithUserState(ctx context.Context, tokenHash string) (GetSessionWithUserStateRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUserState, tokenHash)
	var i GetSessionWithUserStateRow
	err := row.Scan(
		&i.SessionID,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserUsername,
		&i.UserLifecycleState,
	)
	return i, err
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :exec
UPDATE sessions
SET revoked_at = now()
WHERE token_hash = $1
`

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeSessionByTokenHash, tokenHash)
	return err
}

const revokeSessionsByUserID = `-- name: RevokeSessionsByUserID :exec
UPDATE sessions
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

// DisableUser session revocation: every live session of the disabled subject
// is revoked inside the same transaction as the lifecycle CAS.
func (q *Queries) RevokeSessionsByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeSessionsByUserID, userID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_used_at = now(),
    expires_at = $2
WHERE token_hash = $1
`

type TouchSessionParams struct {
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.TokenHash, arg.ExpiresAt)
	return err
}
