// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateUserCAS = `-- name: ActivateUserCAS :one
UPDATE users
SET lifecycle_state = 'active', version = version + 1
WHERE id = $1 AND lifecycle_state = 'provisioning' AND version = $2
RETURNING version
`

type ActivateUserCASParams struct {
	ID      int64 `json:"id"`
	Version int64 `json:"version"`
}

// The only legal transition is provisioning -> active with an expected
// version (iam-application.md ActivateUser); the single-statement UPDATE is
// the atomic CAS — zero rows mean the CAS missed and the service
// distinguishes the failure reason from the current row.
func (q *Queries) ActivateUserCAS(ctx context.Context, arg ActivateUserCASParams) (int64, error) {
	row := q.db.QueryRow(ctx, activateUserCAS, arg.ID, arg.Version)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const bumpUserVersion = `-- name: BumpUserVersion :exec
UPDATE users
SET version = version + 1
WHERE id = $1
`

// Version bump for the admin bootstrap; only called inside a transaction that
// holds the row lock, so `version = version + 1` is race-free.
func (q *Queries) BumpUserVersion(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, bumpUserVersion, id)
	return err
}

const countManagedUsers = `-- name: CountManagedUsers :one
SELECT count(*)
FROM users
WHERE lifecycle_state <> 'provisioning'
  AND (array_length($1::bigint[], 1) IS NULL OR id = ANY($1))
  AND ($2::text = '' OR username ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR account ILIKE '%' || $3 || '%')
`

type CountManagedUsersParams struct {
	Column1 []int64 `json:"column_1"`
	Column2 string  `json:"column_2"`
	Column3 string  `json:"column_3"`
}

func (q *Queries) CountManagedUsers(ctx context.Context, arg CountManagedUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countManagedUsers, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProvisioningUser = `-- name: CreateProvisioningUser :one
INSERT INTO users (username, password_hash, lifecycle_state, version, account, email)
VALUES ($1, $2, 'provisioning', 1, $3, $4)
RETURNING id, username, password_hash, account, email, lifecycle_state, version,
          created_at, updated_at
`

type CreateProvisioningUserParams struct {
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	Account      pgtype.Text `json:"account"`
	Email        pgtype.Text `json:"email"`
}

type CreateProvisioningUserRow struct {
	ID             int64              `json:"id"`
	Username       string             `json:"username"`
	PasswordHash   string             `json:"password_hash"`
	Account        pgtype.Text        `json:"account"`
	Email          pgtype.Text        `json:"email"`
	LifecycleState string             `json:"lifecycle_state"`
	Version        int64              `json:"version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Provisioning identity (US3, iam-application.md CreateProvisioningUser): the
// password hash commits with the row; lifecycle_state/version are explicit
// ('provisioning', 1) because 000006 dropped the temporary defaults.
func (q *Queries) CreateProvisioningUser(ctx context.Context, arg CreateProvisioningUserParams) (CreateProvisioningUserRow, error) {
	row := q.db.QueryRow(ctx, createProvisioningUser,
		arg.Username,
		arg.PasswordHash,
		arg.Account,
		arg.Email,
	)
	var i CreateProvisioningUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Account,
		&i.Email,
		&i.LifecycleState,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, lifecycle_state, version)
VALUES ($1, $2, 'active', 1)
RETURNING id, username, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// 000006 dropped the temporary lifecycle defaults; registration states active
// explicitly and creates version 1 (data-model.md User invariants).
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProvisioningUserCAS = `-- name: DeleteProvisioningUserCAS :one
DELETE FROM users
WHERE id = $1 AND lifecycle_state = 'provisioning' AND version = $2
RETURNING version
`

type DeleteProvisioningUserCASParams struct {
	ID      int64 `json:"id"`
	Version int64 `json:"version"`
}

// CompensateProvisioningUser (iam-application.md CompensateProvisioningUser):
// the single-statement CAS deletes only a still-provisioning subject at the
// expected version — active/disabled/newer-version rows miss and escalate to
// reconciliation. sessions/user_roles cascade away; the tombstone version is
// the deleted prior version + 1.
func (q *Queries) DeleteProvisioningUserCAS(ctx context.Context, arg DeleteProvisioningUserCASParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteProvisioningUserCAS, arg.ID, arg.Version)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const disableUserCAS = `-- name: DisableUserCAS :one
UPDATE users
SET lifecycle_state = 'disabled', version = version + 1
WHERE id = $1 AND lifecycle_state = 'active' AND version = $2
RETURNING version
`

type DisableUserCASParams struct {
	ID      int64 `json:"id"`
	Version int64 `json:"version"`
}

// DisableUser (iam-application.md DisableUser): the only legal transition is
// active -> disabled with an expected version — provisioning subjects are
// handled by CompensateProvisioningUser, re-enable is out of scope. Zero rows
// mean the CAS missed and the service classifies the failure from the current
// row.
func (q *Queries) DisableUserCAS(ctx context.Context, arg DisableUserCASParams) (int64, error) {
	row := q.db.QueryRow(ctx, disableUserCAS, arg.ID, arg.Version)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getProvisioningSnapshot = `-- name: GetProvisioningSnapshot :one
SELECT count(*) AS count, min(created_at) AS oldest_created_at
FROM users
WHERE lifecycle_state = 'provisioning'
`

type GetProvisioningSnapshotRow struct {
	Count           int64       `json:"count"`
	OldestCreatedAt interface{} `json:"oldest_created_at"`
}

// Metrics snapshot (T074): how many identities are still in the
// provisioning lifecycle state and when the oldest one was created.
func (q *Queries) GetProvisioningSnapshot(ctx context.Context) (GetProvisioningSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getProvisioningSnapshot)
	var i GetProvisioningSnapshotRow
	err := row.Scan(&i.Count, &i.OldestCreatedAt)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIDForUpdate = `-- name: GetUserByIDForUpdate :one
SELECT id, username, lifecycle_state, version
FROM users
WHERE id = $1
FOR UPDATE
`

type GetUserByIDForUpdateRow struct {
	ID             int64  `json:"id"`
	Username       string `json:"username"`
	LifecycleState string `json:"lifecycle_state"`
	Version        int64  `json:"version"`
}

// DeleteUsers full-batch precheck (iam-application.md DeleteUsers): locks each
// target row until the deletion transaction commits, so validation and the
// DELETE cannot race a concurrent update (version drift) or a concurrent
// delete (row vanishing mid-batch). Password hash is deliberately NOT selected
// — deletion never touches credentials (least privilege).
func (q *Queries) GetUserByIDForUpdate(ctx context.Context, id int64) (GetUserByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUserByIDForUpdate, id)
	var i GetUserByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.LifecycleState,
		&i.Version,
	)
	return i, err
}

const getUserByIDFull = `-- name: GetUserByIDFull :one
SELECT id, username, password_hash, account, email, lifecycle_state, version,
       created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDFullRow struct {
	ID             int64              `json:"id"`
	Username       string             `json:"username"`
	PasswordHash   string             `json:"password_hash"`
	Account        pgtype.Text        `json:"account"`
	Email          pgtype.Text        `json:"email"`
	LifecycleState string             `json:"lifecycle_state"`
	Version        int64              `json:"version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Full identity aggregate for GetIdentity / GetAuthorizationProfile.
func (q *Queries) GetUserByIDFull(ctx context.Context, id int64) (GetUserByIDFullRow, error) {
	row := q.db.QueryRow(ctx, getUserByIDFull, id)
	var i GetUserByIDFullRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Account,
		&i.Email,
		&i.LifecycleState,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, created_at, updated_at
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsernameAuth = `-- name: GetUserByUsernameAuth :one
SELECT id, username, password_hash, lifecycle_state
FROM users
WHERE username = $1
`

type GetUserByUsernameAuthRow struct {
	ID             int64  `json:"id"`
	Username       string `json:"username"`
	PasswordHash   string `json:"password_hash"`
	LifecycleState string `json:"lifecycle_state"`
}

// IAM authentication lookup: the credentials plus lifecycle state needed by
// Login's uniform-failure checks. (The shared GetUserByUsername above predates
// the lifecycle columns and is left untouched for the legacy services.)
func (q *Queries) GetUserByUsernameAuth(ctx context.Context, username string) (GetUserByUsernameAuthRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameAuth, username)
	var i GetUserByUsernameAuthRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.LifecycleState,
	)
	return i, err
}

const getUserByUsernameForUpdate = `-- name: GetUserByUsernameForUpdate :one
SELECT id, username, lifecycle_state, version
FROM users
WHERE username = $1
FOR UPDATE
`

type GetUserByUsernameForUpdateRow struct {
	ID             int64  `json:"id"`
	Username       string `json:"username"`
	LifecycleState string `json:"lifecycle_state"`
	Version        int64  `json:"version"`
}

// Admin-bootstrap lookup (GrantBuiltInAdminRole): locks the latest user row
// for the duration of the granting transaction so concurrent grants cannot
// race the version bump. Password hash is deliberately NOT selected — the
// bootstrap never touches credentials (least privilege).
func (q *Queries) GetUserByUsernameForUpdate(ctx context.Context, username string) (GetUserByUsernameForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameForUpdate, username)
	var i GetUserByUsernameForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.LifecycleState,
		&i.Version,
	)
	return i, err
}

const listManagedUsers = `-- name: ListManagedUsers :many
SELECT id, username, password_hash, account, email, lifecycle_state, version,
       created_at, updated_at
FROM users
WHERE lifecycle_state <> 'provisioning'
  AND (array_length($1::bigint[], 1) IS NULL OR id = ANY($1))
  AND ($2::text = '' OR username ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR account ILIKE '%' || $3 || '%')
ORDER BY id
LIMIT $4 OFFSET $5
`

type ListManagedUsersParams struct {
	Column1 []int64 `json:"column_1"`
	Column2 string  `json:"column_2"`
	Column3 string  `json:"column_3"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

type ListManagedUsersRow struct {
	ID             int64              `json:"id"`
	Username       string             `json:"username"`
	PasswordHash   string             `json:"password_hash"`
	Account        pgtype.Text        `json:"account"`
	Email          pgtype.Text        `json:"email"`
	LifecycleState string             `json:"lifecycle_state"`
	Version        int64              `json:"version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Managed-user listing (BatchGetManagedIdentities): provisioning users are
// excluded; a NULL candidate array means no id filter; empty candidate arrays
// are short-circuited by the service before reaching the store.
func (q *Queries) ListManagedUsers(ctx context.Context, arg ListManagedUsersParams) ([]ListManagedUsersRow, error) {
	rows, err := q.db.Query(ctx, listManagedUsers,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManagedUsersRow{}
	for rows.Next() {
		var i ListManagedUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Account,
			&i.Email,
			&i.LifecycleState,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateManagedUserCAS = `-- name: UpdateManagedUserCAS :one
UPDATE users
SET username = $2, account = $3, email = $4, version = version + 1
WHERE id = $1 AND version = $5
RETURNING version
`

type UpdateManagedUserCASParams struct {
	ID       int64       `json:"id"`
	Username string      `json:"username"`
	Account  pgtype.Text `json:"account"`
	Email    pgtype.Text `json:"email"`
	Version  int64       `json:"version"`
}

// Managed-user profile update (iam-application.md UpdateManagedUser): the
// statement is the expected-version CAS AND the profile mutation — zero rows
// mean the CAS missed and the service classifies the failure from the current
// row. account/email take the request value verbatim (absent -> NULL); the
// unique username constraint surfaces as a unique violation, never a miss.
// Role replacement and the optional credential change follow in the same
// transaction: this UPDATE locks the row until commit, so the password
// statement below cannot interleave with a concurrent updater.
func (q *Queries) UpdateManagedUserCAS(ctx context.Context, arg UpdateManagedUserCASParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateManagedUserCAS,
		arg.ID,
		arg.Username,
		arg.Account,
		arg.Email,
		arg.Version,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type UpdateUserPasswordHashParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

// Replaces the stored hash; called only inside the transaction whose
// UpdateManagedUserCAS already locked the row (blank/absent password simply
// never calls this — the existing hash is preserved by omission).
func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.ID, arg.PasswordHash)
	return err
}
