// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// The compensation decision is durable before any compensation side effect:
	// running -> compensating with compensation_state pending, lease kept.
	// Returns the affected row count: 0 = stale claim.
	BeginCompensation(ctx context.Context, arg BeginCompensationParams) (int64, error)
	// Same-key authorized HTTP retry before the input deadline
	// (consistency-and-compensation.md): reacquires forward execution by
	// transitioning awaiting_client_input -> running with a fresh lease/token.
	// No attempt is counted until the participant command is actually attempted.
	// Zero rows (deadline passed, state moved on, or key mismatch) surface as
	// ErrStaleClaim and the service re-reads the workflow to classify.
	ClaimAwaitingClientInput(ctx context.Context, arg ClaimAwaitingClientInputParams) (AdminWorkflow, error)
	// Keyed claim (synchronous HTTP path, worker resume, expiry finalization):
	// one specific workflow transitions per the same predicates as
	// ClaimWorkflows — pending/failed_retryable -> running (forward attempt),
	// expired running -> running (reclaim; attempt capped at 10), expired
	// awaiting_client_input -> compensating (expiry finalization, no attempt),
	// expired compensating -> compensating (reclaim; compensation attempt capped
	// at 10, past-deadline rows not claimable — ExhaustToFailedManual covers
	// them). Zero rows = not claimable (live lease, exhausted, past retry
	// deadline, or absent) and surface as ErrStaleClaim; the caller re-reads the
	// workflow to classify.
	ClaimWorkflowByOperationID(ctx context.Context, arg ClaimWorkflowByOperationIDParams) (AdminWorkflow, error)
	// Atomic claim scan (consistency-and-compensation.md lease/retry): leases
	// pending, eligible failed_retryable (next_retry_at due), expired
	// running/compensating (leased_until <= now()) and expired awaiting_client_input
	// (client_input_deadline_at <= now()) rows with owner/lease/fresh claim_token.
	// Forward claims (pending/failed_retryable/expired running) increment
	// attempt_count (capped at 10); expired-input claims transition directly to
	// compensating and do not count as forward attempts; compensation reclaims
	// increment compensation_attempt_count (capped at 10, same retry_deadline
	// ceiling) and never consume the forward budget — a compensation-exhausted or
	// past-deadline compensating row is not claimable (it falls to
	// ExhaustToFailedManual on the resume path).
	ClaimWorkflows(ctx context.Context, arg ClaimWorkflowsParams) ([]AdminWorkflow, error)
	// Manual-recovery terminalization of a failed_manual row: no claim token
	// exists there (FailManual clears it), so recovery completes directly with
	// the same terminal semantics. Recovery may only finalize proven receipts or
	// execute explicitly approved compensation — it never resumes forward
	// execution. 0 rows = not failed_manual (stale) or already terminal.
	CompleteRecoveredWorkflow(ctx context.Context, arg CompleteRecoveredWorkflowParams) (int64, error)
	// Terminal resolution (succeeded/rejected): safe result, lease cleared,
	// completed_at stamped. Compensation convergence (rejected/OPERATION_EXPIRED)
	// also releases subject exclusions — the service does that in the same
	// transaction via UpdateSubjectResult/ReleaseSubjectExclusion. 0 rows = stale.
	CompleteWorkflow(ctx context.Context, arg CompleteWorkflowParams) (int64, error)
	// Metrics snapshot (T074): durable workflow rows in one state — failed
	// (retryable/manual) and compensating states drive the failure gauges.
	CountWorkflowsByState(ctx context.Context, state string) (int64, error)
	// C0/U0/D0: persist a pending workflow BEFORE any participant side effect.
	// retry_deadline_at is supplied by the caller (default creation +24h) and is
	// immutable afterwards; idempotency_key may be NULL for internal operations.
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) error
	// The required credential was not durably committed and is intentionally
	// absent from storage: awaiting_client_input with an immutable deadline
	// (default creation +24h), lease cleared. Waiting consumes no attempt budget;
	// before the deadline only a same-key authorized HTTP retry may continue.
	// 0 rows = stale claim.
	EnterAwaitingClientInput(ctx context.Context, arg EnterAwaitingClientInputParams) (int64, error)
	// Automatic-budget exhaustion (10 attempts / original retry_deadline_at,
	// whichever comes first — forward or compensation counter) transitions a
	// non-live row to failed_manual so reconciliation can proceed; any
	// possibly-applied subject exclusion stays active (recovery decides).
	// Only rows without a live lease transition — a live owner still holds it.
	// 0 rows = not exhausted, live lease, or already terminal; the caller
	// re-reads the workflow to classify.
	ExhaustToFailedManual(ctx context.Context, arg ExhaustToFailedManualParams) (int64, error)
	// Reconciliation: failed_manual, lease cleared, no automatic retry.
	// 0 rows = stale claim.
	FailManual(ctx context.Context, arg FailManualParams) (int64, error)
	// Idempotency scope (operation_type, actor_user_id, idempotency_key) ->
	// one logical workflow (admin_workflows_idempotency_unique).
	GetWorkflowByIdempotencyKey(ctx context.Context, arg GetWorkflowByIdempotencyKeyParams) (AdminWorkflow, error)
	// workflows.sql
	// Workflow-state queries for the Admin BFF workflow store adapter (T051).
	// admin_workflows is BFF-owned (data-model.md Ownership matrix); the store
	// never reads user/department/role facts from here.
	//
	// Every mutation of a claimed workflow is CAS-guarded by
	// (operation_id, state IN ('running','compensating'), claim_token). The CAS
	// statements return the affected row count (`:one` over a count CTE) so the
	// adapter can surface a zero-row miss as ErrStaleClaim — an :exec command tag
	// cannot distinguish "no rows" from "success".
	GetWorkflowByOperationID(ctx context.Context, operationID pgtype.UUID) (AdminWorkflow, error)
	// recovery.sql
	// Append-only manual-reconciliation ledger (T055;
	// contracts/consistency-and-compensation.md Reconciliation; table DDL in
	// 000007). Every manual recovery action is durably recorded before it
	// executes; only insert/list ports exist — the ledger is immutable by
	// construction, and recovery never resumes a revoked/failed actor's forward
	// request.
	InsertRecoveryAction(ctx context.Context, arg InsertRecoveryActionParams) (AdminWorkflowRecoveryAction, error)
	// subjects.sql
	// Per-subject workflow rows (single or batch targets). The partial unique
	// index admin_workflow_subjects_active_unique enforces the no-overlapping-
	// active-workflow exclusion: a unique violation during InsertWorkflowSubject
	// surfaces as ErrSubjectExcluded (OPERATION_IN_PROGRESS) and rejects the
	// whole batch.
	// One active subject row per validated target/version. A re-entry of the SAME
	// workflow (crash recovery between the iam_validated persist and the insert)
	// is idempotent: the conflict index targets the subject, so the DO UPDATE
	// clause narrows the conflict to the same operation_id and returns the row.
	// An active row owned by ANOTHER workflow leaves zero rows (ErrSubjectExcluded
	// -> OPERATION_IN_PROGRESS) and rejects the whole batch.
	InsertWorkflowSubject(ctx context.Context, arg InsertWorkflowSubjectParams) (pgtype.UUID, error)
	ListRecoveryActionsByOperation(ctx context.Context, operationID pgtype.UUID) ([]AdminWorkflowRecoveryAction, error)
	ListSubjectsByOperation(ctx context.Context, operationID pgtype.UUID) ([]AdminWorkflowSubject, error)
	// Durable step persistence (C4/C6/U5/U7/D5): only the current claim holder
	// may persist progress. Nil update fields keep the stored value (COALESCE),
	// so one statement records exactly the fields this step produced. Returns
	// the affected row count: 0 = stale claim.
	PersistStep(ctx context.Context, arg PersistStepParams) (int64, error)
	// Mark a subject row inactive without a tombstone: convergence after
	// compensation (rejected / OPERATION_EXPIRED paths) releases the exclusion.
	ReleaseSubjectExclusion(ctx context.Context, arg ReleaseSubjectExclusionParams) error
	// Bounded automatic retry: failed_retryable with next_retry_at, lease cleared.
	// 0 rows = stale claim.
	RescheduleRetryable(ctx context.Context, arg RescheduleRetryableParams) (int64, error)
	// The restore/compensation side effect failed or conflicted:
	// compensation_state failed (reconciliation follows via FailManual). Like
	// success, the outcome is final — once recorded, neither outcome can be
	// overwritten. 0 rows = stale claim or already-resolved compensation.
	SetCompensationFailed(ctx context.Context, arg SetCompensationFailedParams) (int64, error)
	// The restore/compensation side effect committed: compensation_state
	// succeeded, lease kept until the workflow resolves. The outcome is final:
	// once recorded, neither outcome can be overwritten (0 rows = stale claim or
	// already-resolved compensation).
	SetCompensationSucceeded(ctx context.Context, arg SetCompensationSucceededParams) (int64, error)
	// D5: persist the per-subject tombstone result and release the exclusion.
	UpdateSubjectResult(ctx context.Context, arg UpdateSubjectResultParams) error
	// evidence_cleanup.sql
	// Admin BFF cleanup watermark (data-model.md line 350): the BFF exposes its
	// oldest unresolved/referencing workflow watermark so the Platform coordinator
	// can refuse cleanup while any workflow still references evidence. A workflow
	// is "unresolved/referencing" while it is not terminally resolved OR still
	// holds an active subject exclusion (a possibly-applied effect awaiting
	// reconciliation). Receipts are never purged shorter than the workflows that
	// reference them; the zero-unresolved gate plus the shared 30-day completion
	// floor (a receipt's workflow is created in the same operation) uphold that.
	WorkflowCleanupWatermark(ctx context.Context) (WorkflowCleanupWatermarkRow, error)
}

var _ Querier = (*Queries)(nil)
