// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertRecoveryAction = `-- name: InsertRecoveryAction :one

INSERT INTO admin_workflow_recovery_actions (
    action_id, operation_id, recovery_principal_id, authorization_source,
    approval_id, action_type, reason_code, previous_state, resulting_state,
    safe_result_code, request_id, correlation_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING action_id, operation_id, recovery_principal_id, authorization_source,
          approval_id, action_type, reason_code, previous_state, resulting_state,
          safe_result_code, request_id, correlation_id, created_at
`

type InsertRecoveryActionParams struct {
	ActionID            pgtype.UUID `json:"action_id"`
	OperationID         pgtype.UUID `json:"operation_id"`
	RecoveryPrincipalID string      `json:"recovery_principal_id"`
	AuthorizationSource string      `json:"authorization_source"`
	ApprovalID          pgtype.Text `json:"approval_id"`
	ActionType          string      `json:"action_type"`
	ReasonCode          string      `json:"reason_code"`
	PreviousState       string      `json:"previous_state"`
	ResultingState      string      `json:"resulting_state"`
	SafeResultCode      pgtype.Text `json:"safe_result_code"`
	RequestID           pgtype.Text `json:"request_id"`
	CorrelationID       pgtype.Text `json:"correlation_id"`
}

// recovery.sql
// Append-only manual-reconciliation ledger (T055;
// contracts/consistency-and-compensation.md Reconciliation; table DDL in
// 000007). Every manual recovery action is durably recorded before it
// executes; only insert/list ports exist — the ledger is immutable by
// construction, and recovery never resumes a revoked/failed actor's forward
// request.
func (q *Queries) InsertRecoveryAction(ctx context.Context, arg InsertRecoveryActionParams) (AdminWorkflowRecoveryAction, error) {
	row := q.db.QueryRow(ctx, insertRecoveryAction,
		arg.ActionID,
		arg.OperationID,
		arg.RecoveryPrincipalID,
		arg.AuthorizationSource,
		arg.ApprovalID,
		arg.ActionType,
		arg.ReasonCode,
		arg.PreviousState,
		arg.ResultingState,
		arg.SafeResultCode,
		arg.RequestID,
		arg.CorrelationID,
	)
	var i AdminWorkflowRecoveryAction
	err := row.Scan(
		&i.ActionID,
		&i.OperationID,
		&i.RecoveryPrincipalID,
		&i.AuthorizationSource,
		&i.ApprovalID,
		&i.ActionType,
		&i.ReasonCode,
		&i.PreviousState,
		&i.ResultingState,
		&i.SafeResultCode,
		&i.RequestID,
		&i.CorrelationID,
		&i.CreatedAt,
	)
	return i, err
}

const listRecoveryActionsByOperation = `-- name: ListRecoveryActionsByOperation :many
SELECT action_id, operation_id, recovery_principal_id, authorization_source,
       approval_id, action_type, reason_code, previous_state, resulting_state,
       safe_result_code, request_id, correlation_id, created_at
FROM admin_workflow_recovery_actions
WHERE operation_id = $1
ORDER BY created_at, action_id
`

func (q *Queries) ListRecoveryActionsByOperation(ctx context.Context, operationID pgtype.UUID) ([]AdminWorkflowRecoveryAction, error) {
	rows, err := q.db.Query(ctx, listRecoveryActionsByOperation, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminWorkflowRecoveryAction{}
	for rows.Next() {
		var i AdminWorkflowRecoveryAction
		if err := rows.Scan(
			&i.ActionID,
			&i.OperationID,
			&i.RecoveryPrincipalID,
			&i.AuthorizationSource,
			&i.ApprovalID,
			&i.ActionType,
			&i.ReasonCode,
			&i.PreviousState,
			&i.ResultingState,
			&i.SafeResultCode,
			&i.RequestID,
			&i.CorrelationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
