// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subjects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertWorkflowSubject = `-- name: InsertWorkflowSubject :one

INSERT INTO admin_workflow_subjects (operation_id, subject_user_id, expected_iam_version)
VALUES ($1, $2, $3)
ON CONFLICT (subject_user_id) WHERE active
DO UPDATE SET expected_iam_version = EXCLUDED.expected_iam_version
WHERE admin_workflow_subjects.operation_id = EXCLUDED.operation_id
RETURNING operation_id
`

type InsertWorkflowSubjectParams struct {
	OperationID        pgtype.UUID `json:"operation_id"`
	SubjectUserID      int64       `json:"subject_user_id"`
	ExpectedIamVersion int64       `json:"expected_iam_version"`
}

// subjects.sql
// Per-subject workflow rows (single or batch targets). The partial unique
// index admin_workflow_subjects_active_unique enforces the no-overlapping-
// active-workflow exclusion: a unique violation during InsertWorkflowSubject
// surfaces as ErrSubjectExcluded (OPERATION_IN_PROGRESS) and rejects the
// whole batch.
// One active subject row per validated target/version. A re-entry of the SAME
// workflow (crash recovery between the iam_validated persist and the insert)
// is idempotent: the conflict index targets the subject, so the DO UPDATE
// clause narrows the conflict to the same operation_id and returns the row.
// An active row owned by ANOTHER workflow leaves zero rows (ErrSubjectExcluded
// -> OPERATION_IN_PROGRESS) and rejects the whole batch.
func (q *Queries) InsertWorkflowSubject(ctx context.Context, arg InsertWorkflowSubjectParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertWorkflowSubject, arg.OperationID, arg.SubjectUserID, arg.ExpectedIamVersion)
	var operation_id pgtype.UUID
	err := row.Scan(&operation_id)
	return operation_id, err
}

const listSubjectsByOperation = `-- name: ListSubjectsByOperation :many
SELECT operation_id, subject_user_id, expected_iam_version,
       resulting_tombstone_version, active
FROM admin_workflow_subjects
WHERE operation_id = $1
ORDER BY subject_user_id
`

func (q *Queries) ListSubjectsByOperation(ctx context.Context, operationID pgtype.UUID) ([]AdminWorkflowSubject, error) {
	rows, err := q.db.Query(ctx, listSubjectsByOperation, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminWorkflowSubject{}
	for rows.Next() {
		var i AdminWorkflowSubject
		if err := rows.Scan(
			&i.OperationID,
			&i.SubjectUserID,
			&i.ExpectedIamVersion,
			&i.ResultingTombstoneVersion,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseSubjectExclusion = `-- name: ReleaseSubjectExclusion :exec
UPDATE admin_workflow_subjects
SET active = false
WHERE operation_id = $1 AND subject_user_id = $2
`

type ReleaseSubjectExclusionParams struct {
	OperationID   pgtype.UUID `json:"operation_id"`
	SubjectUserID int64       `json:"subject_user_id"`
}

// Mark a subject row inactive without a tombstone: convergence after
// compensation (rejected / OPERATION_EXPIRED paths) releases the exclusion.
func (q *Queries) ReleaseSubjectExclusion(ctx context.Context, arg ReleaseSubjectExclusionParams) error {
	_, err := q.db.Exec(ctx, releaseSubjectExclusion, arg.OperationID, arg.SubjectUserID)
	return err
}

const updateSubjectResult = `-- name: UpdateSubjectResult :exec
UPDATE admin_workflow_subjects
SET resulting_tombstone_version = $3, active = false
WHERE operation_id = $1 AND subject_user_id = $2
`

type UpdateSubjectResultParams struct {
	OperationID               pgtype.UUID `json:"operation_id"`
	SubjectUserID             int64       `json:"subject_user_id"`
	ResultingTombstoneVersion pgtype.Int8 `json:"resulting_tombstone_version"`
}

// D5: persist the per-subject tombstone result and release the exclusion.
func (q *Queries) UpdateSubjectResult(ctx context.Context, arg UpdateSubjectResultParams) error {
	_, err := q.db.Exec(ctx, updateSubjectResult, arg.OperationID, arg.SubjectUserID, arg.ResultingTombstoneVersion)
	return err
}
