// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bridge_mode.sql

package sqlc

import (
	"context"
)

const getCompatibilityBridgeMode = `-- name: GetCompatibilityBridgeMode :one

SELECT id, legacy_delete_sync_enabled, version, updated_at
FROM compatibility_bridge_mode
WHERE id = 1
`

// Platform-owned single-row bridge mode (migration 000008). The startup
// gate (cmd/server) reads it to verify legacy_delete_sync_enabled=false
// before accepting the delete consumer/dispatcher or the BFF /users/delete
// route (plan Phase 5.9 step 4). Writes never happen through this package:
// controlled transitions go through set_legacy_delete_sync_mode (T076).
func (q *Queries) GetCompatibilityBridgeMode(ctx context.Context) (CompatibilityBridgeMode, error) {
	row := q.db.QueryRow(ctx, getCompatibilityBridgeMode)
	var i CompatibilityBridgeMode
	err := row.Scan(
		&i.ID,
		&i.LegacyDeleteSyncEnabled,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const setLegacyDeleteSyncMode = `-- name: SetLegacyDeleteSyncMode :one
SELECT set_legacy_delete_sync_mode(
    $1, $2, $3, $4, $5, $6, $7, $8
) AS version
`

type SetLegacyDeleteSyncModeParams struct {
	PExpectedVersion     int64  `json:"p_expected_version"`
	PEnabled             bool   `json:"p_enabled"`
	PPrincipalID         string `json:"p_principal_id"`
	PAuthorizationSource string `json:"p_authorization_source"`
	PApprovalID          string `json:"p_approval_id"`
	PReasonCode          string `json:"p_reason_code"`
	PRequestID           string `json:"p_request_id"`
	PCorrelationID       string `json:"p_correlation_id"`
}

// Controlled bridge-mode transition (T076): runs the Platform-owned SECURITY
// DEFINER function which CAS-bumps the mode row, appends the immutable
// compatibility_bridge_mode_changes audit row and returns the resulting
// version. An idempotent replay whose target is already achieved returns the
// current version; a stale CAS with a different target raises.
func (q *Queries) SetLegacyDeleteSyncMode(ctx context.Context, arg SetLegacyDeleteSyncModeParams) (int64, error) {
	row := q.db.QueryRow(ctx, setLegacyDeleteSyncMode,
		arg.PExpectedVersion,
		arg.PEnabled,
		arg.PPrincipalID,
		arg.PAuthorizationSource,
		arg.PApprovalID,
		arg.PReasonCode,
		arg.PRequestID,
		arg.PCorrelationID,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}
