// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: departments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDepartmentsByParentID = `-- name: CountDepartmentsByParentID :one
SELECT count(*) FROM departments WHERE parent_id = $1
`

func (q *Queries) CountDepartmentsByParentID(ctx context.Context, parentID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countDepartmentsByParentID, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByDepartmentID = `-- name: CountUsersByDepartmentID :one
SELECT count(*) FROM users WHERE department_id = $1
`

func (q *Queries) CountUsersByDepartmentID(ctx context.Context, departmentID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByDepartmentID, departmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (name, parent_id)
VALUES ($1, $2)
RETURNING id, name, parent_id, created_at, updated_at
`

type CreateDepartmentParams struct {
	Name     string      `json:"name"`
	ParentID pgtype.Int8 `json:"parent_id"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment, arg.Name, arg.ParentID)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM departments
WHERE id = $1
`

func (q *Queries) DeleteDepartment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDepartment, id)
	return err
}

const getDepartmentByID = `-- name: GetDepartmentByID :one
SELECT id, name, parent_id, created_at, updated_at
FROM departments
WHERE id = $1
`

func (q *Queries) GetDepartmentByID(ctx context.Context, id int64) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByID, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepartmentByName = `-- name: GetDepartmentByName :one
SELECT id, name, parent_id, created_at, updated_at
FROM departments
WHERE name = $1
`

func (q *Queries) GetDepartmentByName(ctx context.Context, name string) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByName, name)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many

SELECT id, name, parent_id, created_at, updated_at
FROM departments
ORDER BY id
`

// departments.sql
// Queries for the departments table (self-referencing tree).
func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Department{}
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments
SET name = $2, parent_id = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, parent_id, created_at, updated_at
`

type UpdateDepartmentParams struct {
	ID       int64       `json:"id"`
	Name     string      `json:"name"`
	ParentID pgtype.Int8 `json:"parent_id"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment, arg.ID, arg.Name, arg.ParentID)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
