// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence_cleanup.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finalizeCleanupAudit = `-- name: FinalizeCleanupAudit :one
SELECT public.finalize_cleanup_audit($1::uuid, $2, $3::jsonb, $4)
`

type FinalizeCleanupAuditParams struct {
	Column1        pgtype.UUID `json:"column_1"`
	PStatus        string      `json:"p_status"`
	Column3        []byte      `json:"column_3"`
	PBlockedReason string      `json:"p_blocked_reason"`
}

func (q *Queries) FinalizeCleanupAudit(ctx context.Context, arg FinalizeCleanupAuditParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, finalizeCleanupAudit,
		arg.Column1,
		arg.PStatus,
		arg.Column3,
		arg.PBlockedReason,
	)
	var finalize_cleanup_audit pgtype.UUID
	err := row.Scan(&finalize_cleanup_audit)
	return finalize_cleanup_audit, err
}

const recordCleanupAudit = `-- name: RecordCleanupAudit :one

SELECT public.record_cleanup_audit(
    $1::uuid, $2, $3, $4, $5, $6, $7::timestamptz, $8::timestamptz, $9::jsonb)
`

type RecordCleanupAuditParams struct {
	Column1              pgtype.UUID        `json:"column_1"`
	PApprovalID          string             `json:"p_approval_id"`
	PPrincipalID         string             `json:"p_principal_id"`
	PAuthorizationSource string             `json:"p_authorization_source"`
	PRequestID           string             `json:"p_request_id"`
	PCorrelationID       string             `json:"p_correlation_id"`
	Column7              pgtype.Timestamptz `json:"column_7"`
	Column8              pgtype.Timestamptz `json:"column_8"`
	Column9              []byte             `json:"column_9"`
}

// evidence_cleanup.sql
// Platform evidence-cleanup audit (T078): the immutable
// platform_evidence_cleanup_audit table (migration 000013) is written only
// through the two SECURITY DEFINER functions, so no runtime login can touch
// the audit directly. Caller identity fields come from the trusted Platform
// operations context, never from caller-supplied display text.
func (q *Queries) RecordCleanupAudit(ctx context.Context, arg RecordCleanupAuditParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, recordCleanupAudit,
		arg.Column1,
		arg.PApprovalID,
		arg.PPrincipalID,
		arg.PAuthorizationSource,
		arg.PRequestID,
		arg.PCorrelationID,
		arg.Column7,
		arg.Column8,
		arg.Column9,
	)
	var record_cleanup_audit pgtype.UUID
	err := row.Scan(&record_cleanup_audit)
	return record_cleanup_audit, err
}
