// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package sqlc

import (
	"context"
)

const healthCheck = `-- name: HealthCheck :one

SELECT 1 AS healthy
`

// Health check query for sqlc.
// Used to verify database connectivity during readiness checks.
// Currently unused by scaffold (health check uses pgx Ping directly),
// but serves as a sqlc query placeholder for future database-dependent checks.
func (q *Queries) HealthCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, healthCheck)
	var healthy int32
	err := row.Scan(&healthy)
	return healthy, err
}
