// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package sqlc

import (
	"context"
)

const hasPermissionByUserID = `-- name: HasPermissionByUserID :one
SELECT EXISTS (
    SELECT 1
    FROM user_roles ur
    JOIN role_permissions rp ON rp.role_id = ur.role_id
    JOIN permissions p ON p.id = rp.permission_id
    WHERE ur.user_id = $1
      AND p.code = $2
) AS has_permission
`

type HasPermissionByUserIDParams struct {
	UserID int64  `json:"user_id"`
	Code   string `json:"code"`
}

func (q *Queries) HasPermissionByUserID(ctx context.Context, arg HasPermissionByUserIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPermissionByUserID, arg.UserID, arg.Code)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const listEffectivePermissionsByUserID = `-- name: ListEffectivePermissionsByUserID :many

SELECT DISTINCT p.code
FROM user_roles ur
JOIN role_permissions rp ON rp.role_id = ur.role_id
JOIN permissions p ON p.id = rp.permission_id
WHERE ur.user_id = $1
ORDER BY p.code
`

// permissions.sql
// Effective permissions are the distinct union of grants from all user roles.
func (q *Queries) ListEffectivePermissionsByUserID(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listEffectivePermissionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
