// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// Health check query for sqlc.
	// Used to verify database connectivity during readiness checks.
	// Currently unused by scaffold (health check uses pgx Ping directly),
	// but serves as a sqlc query placeholder for future database-dependent checks.
	HealthCheck(ctx context.Context) (int32, error)
	RevokeSessionByTokenHash(ctx context.Context, tokenHash string) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
}

var _ Querier = (*Queries)(nil)
