// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rollout_gate.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveRouteDisable = `-- name: ApproveRouteDisable :one
SELECT approve_route_disable(
    $1, $2, $3, $4
) AS gate_id
`

type ApproveRouteDisableParams struct {
	PPhase       string             `json:"p_phase"`
	PApprovalID  string             `json:"p_approval_id"`
	PPrincipalID string             `json:"p_principal_id"`
	PObservedAt  pgtype.Timestamptz `json:"p_observed_at"`
}

func (q *Queries) ApproveRouteDisable(ctx context.Context, arg ApproveRouteDisableParams) (int64, error) {
	row := q.db.QueryRow(ctx, approveRouteDisable,
		arg.PPhase,
		arg.PApprovalID,
		arg.PPrincipalID,
		arg.PObservedAt,
	)
	var gate_id int64
	err := row.Scan(&gate_id)
	return gate_id, err
}

const recordRolloutGateSample = `-- name: RecordRolloutGateSample :one
SELECT record_rollout_gate_sample(
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) AS gate_id
`

type RecordRolloutGateSampleParams struct {
	PPhase                         string             `json:"p_phase"`
	PCapabilityManifestHash        string             `json:"p_capability_manifest_hash"`
	PBridgeModeVersion             int64              `json:"p_bridge_mode_version"`
	PBridgeLegacyDeleteSyncEnabled bool               `json:"p_bridge_legacy_delete_sync_enabled"`
	PLegacyRows                    int64              `json:"p_legacy_rows"`
	PNewRows                       int64              `json:"p_new_rows"`
	PRowVersionChecksum            string             `json:"p_row_version_checksum"`
	PMismatchCount                 int64              `json:"p_mismatch_count"`
	PLastMismatchAt                pgtype.Timestamptz `json:"p_last_mismatch_at"`
	PRollbackArtifactID            string             `json:"p_rollback_artifact_id"`
	PRollbackSuiteResult           string             `json:"p_rollback_suite_result"`
	PPrincipalID                   string             `json:"p_principal_id"`
	PObservedAt                    pgtype.Timestamptz `json:"p_observed_at"`
	PMaxGapInterval                pgtype.Interval    `json:"p_max_gap_interval"`
}

func (q *Queries) RecordRolloutGateSample(ctx context.Context, arg RecordRolloutGateSampleParams) (int64, error) {
	row := q.db.QueryRow(ctx, recordRolloutGateSample,
		arg.PPhase,
		arg.PCapabilityManifestHash,
		arg.PBridgeModeVersion,
		arg.PBridgeLegacyDeleteSyncEnabled,
		arg.PLegacyRows,
		arg.PNewRows,
		arg.PRowVersionChecksum,
		arg.PMismatchCount,
		arg.PLastMismatchAt,
		arg.PRollbackArtifactID,
		arg.PRollbackSuiteResult,
		arg.PPrincipalID,
		arg.PObservedAt,
		arg.PMaxGapInterval,
	)
	var gate_id int64
	err := row.Scan(&gate_id)
	return gate_id, err
}
