// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_rbac.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersByDepartment = `-- name: CountUsersByDepartment :one
SELECT count(*)
FROM users
WHERE ($1::bigint = 0 OR department_id = $1)
  AND ($2::text = '' OR username ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR account ILIKE '%' || $3 || '%')
`

type CountUsersByDepartmentParams struct {
	Column1 int64  `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) CountUsersByDepartment(ctx context.Context, arg CountUsersByDepartmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByDepartment, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRbacUser = `-- name: CreateRbacUser :one

INSERT INTO users (username, password_hash, account, email, department_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, password_hash, account, email, department_id, created_at, updated_at
`

type CreateRbacUserParams struct {
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	Account      pgtype.Text `json:"account"`
	Email        pgtype.Text `json:"email"`
	DepartmentID pgtype.Int8 `json:"department_id"`
}

type CreateRbacUserRow struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Account      pgtype.Text        `json:"account"`
	Email        pgtype.Text        `json:"email"`
	DepartmentID pgtype.Int8        `json:"department_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// users_rbac.sql
// User-management queries: create/update/delete users, paginated listing,
// and the user<->role join. Query names avoid colliding with the existing
// auth-focused CreateUser / GetUserByUsername / GetUserByID.
func (q *Queries) CreateRbacUser(ctx context.Context, arg CreateRbacUserParams) (CreateRbacUserRow, error) {
	row := q.db.QueryRow(ctx, createRbacUser,
		arg.Username,
		arg.PasswordHash,
		arg.Account,
		arg.Email,
		arg.DepartmentID,
	)
	var i CreateRbacUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Account,
		&i.Email,
		&i.DepartmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserRolesByUserID = `-- name: DeleteUserRolesByUserID :exec
DELETE FROM user_roles WHERE user_id = $1
`

func (q *Queries) DeleteUserRolesByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserRolesByUserID, userID)
	return err
}

const getUserFullByID = `-- name: GetUserFullByID :one
SELECT id, username, password_hash, account, email, department_id, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserFullByIDRow struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Account      pgtype.Text        `json:"account"`
	Email        pgtype.Text        `json:"email"`
	DepartmentID pgtype.Int8        `json:"department_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserFullByID(ctx context.Context, id int64) (GetUserFullByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserFullByID, id)
	var i GetUserFullByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Account,
		&i.Email,
		&i.DepartmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserRole = `-- name: InsertUserRole :exec
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
ON CONFLICT (user_id, role_id) DO NOTHING
`

type InsertUserRoleParams struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}

func (q *Queries) InsertUserRole(ctx context.Context, arg InsertUserRoleParams) error {
	_, err := q.db.Exec(ctx, insertUserRole, arg.UserID, arg.RoleID)
	return err
}

const listRolesByUserID = `-- name: ListRolesByUserID :many
SELECT r.id, r.name, r.code
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.id
`

type ListRolesByUserIDRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Code string `json:"code"`
}

func (q *Queries) ListRolesByUserID(ctx context.Context, userID int64) ([]ListRolesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listRolesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesByUserIDRow{}
	for rows.Next() {
		var i ListRolesByUserIDRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByDepartment = `-- name: ListUsersByDepartment :many
SELECT id, username, password_hash, account, email, department_id, created_at, updated_at
FROM users
WHERE ($1::bigint = 0 OR department_id = $1)
  AND ($2::text = '' OR username ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR account ILIKE '%' || $3 || '%')
ORDER BY id
LIMIT $4 OFFSET $5
`

type ListUsersByDepartmentParams struct {
	Column1 int64  `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListUsersByDepartmentRow struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Account      pgtype.Text        `json:"account"`
	Email        pgtype.Text        `json:"email"`
	DepartmentID pgtype.Int8        `json:"department_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUsersByDepartment(ctx context.Context, arg ListUsersByDepartmentParams) ([]ListUsersByDepartmentRow, error) {
	rows, err := q.db.Query(ctx, listUsersByDepartment,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByDepartmentRow{}
	for rows.Next() {
		var i ListUsersByDepartmentRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Account,
			&i.Email,
			&i.DepartmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRbacUser = `-- name: UpdateRbacUser :one
UPDATE users
SET account = $2, email = $3, department_id = $4, updated_at = now()
WHERE id = $1
RETURNING id, username, password_hash, account, email, department_id, created_at, updated_at
`

type UpdateRbacUserParams struct {
	ID           int64       `json:"id"`
	Account      pgtype.Text `json:"account"`
	Email        pgtype.Text `json:"email"`
	DepartmentID pgtype.Int8 `json:"department_id"`
}

type UpdateRbacUserRow struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Account      pgtype.Text        `json:"account"`
	Email        pgtype.Text        `json:"email"`
	DepartmentID pgtype.Int8        `json:"department_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateRbacUser(ctx context.Context, arg UpdateRbacUserParams) (UpdateRbacUserRow, error) {
	row := q.db.QueryRow(ctx, updateRbacUser,
		arg.ID,
		arg.Account,
		arg.Email,
		arg.DepartmentID,
	)
	var i UpdateRbacUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Account,
		&i.Email,
		&i.DepartmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
